# Q8: Scrape data for first 100 sneakers you find when you visit flipkart.com and search for “sneakers” in the search field.
You have to scrape 4 attributes of each sneaker :
1. Brand
2. Product Description
3. Price
4. discount %
As shown in the below image, you have to scrape the tick marked attributes.
Also note that all the steps required during scraping should be done through code 
only and not manually

In [2]:
import selenium
from selenium import webdriver 
driver=webdriver.Chrome("chromedriver1.exe")
url="https://www.flipkart.com"
driver.get(url)

In [3]:
search_job=driver.find_element_by_xpath("//input[@title='Search for products, brands and more']")
search_job

In [4]:
search_job.send_keys("sneakers")

In [5]:
search_button=driver.find_element_by_xpath("//button[@class='L0Z3Pu']")
search_button.click()

In [6]:
Brand_name1=driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
Brand_name1
Brand_name2=[]

for i in Brand_name1:
    Brand_name2.append(i.text)
Brand_name2

Product_des1=driver.find_elements_by_xpath("//a[@class='IRpwTa']")
Product_des1
Product_des2=[]

for i in Product_des1:
    Product_des2.append(i.text)
Product_des2

Price1=driver.find_elements_by_xpath("//div[@class='_30jeq3']")
Price1
Price2=[]

for i in Price1:
    Price2.append(i.text)
Price2

Discount1=driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']")
Discount1
Discount2=[]

for i in Discount1:
    Discount2.append(i.text)
Discount2

['57% off',
 '59% off',
 '64% off',
 '86% off',
 '52% off',
 '75% off',
 '66% off',
 '60% off',
 '70% off',
 '60% off',
 '28% off',
 '65% off',
 '60% off',
 '50% off',
 '66% off',
 '65% off',
 '77% off',
 '65% off',
 '65% off',
 '80% off',
 '51% off',
 '55% off',
 '52% off',
 '68% off',
 '60% off',
 '55% off',
 '47% off',
 '57% off',
 '60% off',
 '60% off',
 '53% off',
 '80% off',
 '81% off',
 '65% off',
 '62% off',
 '75% off',
 '50% off',
 '52% off',
 '7% off',
 '60% off']

In [7]:
second_page=driver.find_element_by_xpath('//nav/a[@class="_1LKTO3" ]/span[text() = "Next"]')
second_page1=second_page.click()

In [8]:
Brand_name3=driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
Brand_name3
Brand_name4=[]

for i in Brand_name3:
    Brand_name4.append(i.text)
Brand_name4

Product_des3=driver.find_elements_by_xpath("//a[@class='IRpwTa']")
Product_des4=[]

for i in Product_des3:
    Product_des4.append(i.text)


Price3=driver.find_elements_by_xpath("//div[@class='_30jeq3']")
Price4=[]

for i in Price3:
    Price4.append(i.text)


Discount3=driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']")
Discount4=[]

for i in Discount3:
    Discount4.append(i.text)
Discount4

['55% off',
 '51% off',
 '72% off',
 '63% off',
 '52% off',
 '23% off',
 '52% off',
 '46% off',
 '73% off',
 '39% off',
 '47% off',
 '60% off',
 '82% off',
 '60% off',
 '71% off',
 '51% off',
 '16% off',
 '55% off',
 '81% off',
 '61% off',
 '69% off',
 '36% off',
 '28% off',
 '60% off',
 '37% off',
 '56% off',
 '60% off',
 '55% off',
 '17% off',
 '60% off',
 '75% off',
 '66% off',
 '50% off',
 '80% off',
 '68% off',
 '83% off',
 '60% off',
 '26% off',
 '55% off',
 '67% off']

In [9]:
second_page=driver.find_element_by_xpath('//nav/a[@class="_1LKTO3" ]/span[text() = "Next"]')
second_page1=second_page.click()

In [10]:
Brand_name5=driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
Brand_name6=[]

for i in Brand_name5:
    Brand_name6.append(i.text)


Product_des5=driver.find_elements_by_xpath("//a[@class='IRpwTa']")
Product_des6=[]

for i in Product_des5:
    Product_des6.append(i.text)


Price5=driver.find_elements_by_xpath("//div[@class='_30jeq3']")
Price6=[]

for i in Price5:
    Price6.append(i.text)


Discount5=driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']")
Discount6=[]

for i in Discount5:
    Discount6.append(i.text)
Discount6

['17% off',
 '51% off',
 '43% off',
 '64% off',
 '23% off',
 '64% off',
 '56% off',
 '23% off',
 '55% off',
 '62% off',
 '63% off',
 '20% off',
 '55% off',
 '37% off',
 '23% off',
 '63% off',
 '65% off',
 '10% off',
 '55% off',
 '43% off',
 '85% off',
 '47% off',
 '49% off',
 '15% off',
 '61% off',
 '61% off',
 '52% off',
 '23% off',
 '43% off',
 '69% off',
 '49% off',
 '28% off',
 '57% off',
 '23% off',
 '40% off',
 '74% off',
 '70% off',
 '55% off',
 '69% off',
 '80% off']

In [11]:
Brand_name=Brand_name2+Brand_name4+Brand_name6
Product_des=Product_des2+Product_des4+Product_des6
Price=Price2+Price4+Price6
Discount=Discount2+Discount4+Discount6

In [15]:
import pandas as pd
Sneakers=pd.DataFrame({})
Sneakers["Brand_name"]=Brand_name[0:100]
Sneakers["Product_Description"]=Product_des[0:100]
Sneakers["Price"]=Price[0:100]
Sneakers["Discount"]=Discount[0:100]

In [16]:
Sneakers

,Brand_name,Product_Description,Price,Discount
0,Echor,Men's Sneakers Walking Shoes - Lightweight Cla...,₹429,57% off
1,DUCATI,Sneakers For Men,"₹1,499",59% off
2,Magnolia,Sneakers For Men,₹356,64% off
3,BRUTON,Combo Pack Of 4 Casual Shoes Loafer Shoes Snea...,₹474,86% off
4,Longwalk,Men Boxer Sneakers For Men,₹236,52% off
...,...,...,...,...
95,SHOEFLY,Mega IDP Sneakers For Men,₹362,63% off
96,PUMA,Casual Sneakers Sneakers For Men,"₹1,047",65% off
97,SPARX,Sneakers For Men,₹809,10% off
98,bluemaker,White Sneakers | Top Rated Shoes | Gym Shoes |...,₹449,55% off
99,BIRDE,Combo Men Pack of 2 Loafers Shoes Sneakers For...,₹283,43% off