# DELHI-KOLKATTA -01-02-2022

In [1]:
!pip install selenium
!pip install undetected-chromedriver
     

import time
import warnings
warnings.filterwarnings('ignore')

Requirement already satisfied: selenium in c:\users\admin\anaconda3\lib\site-packages (3.141.0)
Requirement already satisfied: urllib3 in c:\users\admin\anaconda3\lib\site-packages (from selenium) (1.25.11)
Requirement already satisfied: undetected-chromedriver in c:\users\admin\anaconda3\lib\site-packages (3.0.6)
Requirement already satisfied: websockets in c:\users\admin\anaconda3\lib\site-packages (from undetected-chromedriver) (10.1)
Requirement already satisfied: selenium in c:\users\admin\anaconda3\lib\site-packages (from undetected-chromedriver) (3.141.0)
Requirement already satisfied: requests in c:\users\admin\anaconda3\lib\site-packages (from undetected-chromedriver) (2.24.0)
Requirement already satisfied: urllib3 in c:\users\admin\anaconda3\lib\site-packages (from selenium->undetected-chromedriver) (1.25.11)
Requirement already satisfied: idna<3,>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from requests->undetected-chromedriver) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\anaconda3\lib\site-packages (from requests->undetected-chromedriver) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\admin\anaconda3\lib\site-packages (from requests->undetected-chromedriver) (3.0.4)

In [2]:
import selenium
import pandas as pd
from selenium import webdriver 
from selenium.common.exceptions import  StaleElementReferenceException,ElementClickInterceptedException
from selenium.common.exceptions import  NoSuchElementException,NoSuchWindowException

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

In [3]:
driver=webdriver.Chrome(r"C:\Users\Admin\Downloads\chromedriver_win32 (2)\chromedriver.exe")

In [4]:
url="https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-CCU-01/02/2022&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1643468880339&forwardFlowRequired=true&mpo=&intl=false"
driver.get(url)

In [5]:
for i in url:
    SCROLL_PAUSE_TIME = 1

    # Get scroll height
    """last_height = driver.execute_script("return document.body.scrollHeight")

    this dowsnt work due to floating web elements on youtube
    """

    last_height = driver.execute_script("return document.documentElement.scrollHeight")
    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0,document.documentElement.scrollHeight);")

        # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.documentElement.scrollHeight")
        if new_height == last_height:
                 break
        last_height = new_height

In [6]:
Company_name1=driver.find_elements_by_xpath('//span[@class="boldFont blackText airlineName"]')
Company_name1
Company_name2=[]

for i in Company_name1:
    Company_name2.append(i.text)
Company_name2

['Go First',
 'Spicejet',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Spicejet',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air India',
 'IndiGo',
 'AirAsia',
 'Vistara',
 'IndiGo, Vistara',
 'Air India, Vistara',
 'Vistara']

In [7]:
time1=driver.find_elements_by_xpath('//p[@class="blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter"]')
time1
time2=[]

for i in time1:
    time2.append(i.text)
time2

['09:15',
 '15:50',
 '10:15',
 '21:30',
 '19:55',
 '04:00',
 '18:20',
 '04:00',
 '16:35',
 '04:00',
 '19:55',
 '08:40',
 '16:40',
 '08:40',
 '19:20',
 '21:25',
 '07:25',
 '13:10',
 '12:35',
 '17:50',
 '14:40',
 '19:50',
 '09:15',
 '19:50',
 '16:05',
 '20:15',
 '13:15',
 '20:15',
 '16:45',
 '22:55',
 '22:00',
 '00:05',
 '12:20',
 '20:15',
 '08:00',
 '19:45',
 '13:40',
 '20:45',
 '15:45',
 '20:45',
 '13:15',
 '20:45',
 '17:30',
 '20:45']

In [8]:
departure_time=[]
for i in range(0,len(time2),2):
    departure_time.append(time2[i])
departure_time

['09:15',
 '10:15',
 '19:55',
 '18:20',
 '16:35',
 '19:55',
 '16:40',
 '19:20',
 '07:25',
 '12:35',
 '14:40',
 '09:15',
 '16:05',
 '13:15',
 '16:45',
 '22:00',
 '12:20',
 '08:00',
 '13:40',
 '15:45',
 '13:15',
 '17:30']

In [9]:
arrivaltime=[]
for i in range(1,len(time2),2):
    arrivaltime.append(time2[i])
arrivaltime

['15:50',
 '21:30',
 '04:00',
 '04:00',
 '04:00',
 '08:40',
 '08:40',
 '21:25',
 '13:10',
 '17:50',
 '19:50',
 '19:50',
 '20:15',
 '20:15',
 '22:55',
 '00:05',
 '20:15',
 '19:45',
 '20:45',
 '20:45',
 '20:45',
 '20:45']

In [10]:
place=driver.find_elements_by_xpath('//p[@class="darkText"]')
place1=[]

for i in place:
    place1.append(i.text)
place1

['New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata',
 'New Delhi',
 'Kolkata']

In [11]:
departureplace=[]
for i in range(0,len(place1),2):
    departureplace.append(place1[i])
departureplace

['New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi']

In [12]:
Arrivalplace=[]
for i in range(1,len(place1),2):
    Arrivalplace.append(place1[i])
Arrivalplace

['Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata']

In [13]:
timmings=driver.find_elements_by_xpath('//div[@class="stop-info flexOne"]')
timmings
timmings1=[]

for i in timmings:
    timmings1.append(i.text.replace("\n",","))
timmings1

['06 h 35 m,1 stop via Bagdogra',
 '11 h 15 m,1 stop via Guwahati',
 '08 h 05 m,1 stop via Pune',
 '09 h 40 m,1 stop via Pune',
 '11 h 25 m,1 stop via Pune',
 '12 h 45 m,1 stop via Ahmedabad',
 '16 h,1 stop via Ahmedabad',
 '26 h 05 m,1 stop via Jaipur',
 '05 h 45 m,1 stop via Jaipur',
 '05 h 15 m,1 stop via Lucknow',
 '05 h 10 m,1 stop via Raipur',
 '10 h 35 m,1 stop via Raipur',
 '04 h 10 m,1 stop via Patna',
 '07 h,1 stop via Patna',
 '06 h 10 m,1 stop via Bhubaneswar',
 '02 h 05 m,Non stop',
 '07 h 55 m,1 stop via Patna',
 '11 h 45 m,1 stop via Bengaluru',
 '07 h 05 m,1 stop via Lucknow',
 '05 h,1 stop via Lucknow',
 '07 h 30 m,2 stop via Gorakhpur,Lucknow',
 '03 h 15 m,1 stop via Lucknow']

In [14]:
price=driver.find_elements_by_xpath('//div[@class="textRight flexOne"]')
price
price1=[]

for i in price:
    price1.append(i.text)
price1

['₹ 5,954',
 '₹ 5,954',
 '₹ 5,954',
 '₹ 5,954',
 '₹ 5,954',
 '₹ 5,954',
 '₹ 5,954',
 '₹ 5,954',
 '₹ 5,955',
 '₹ 5,955',
 '₹ 5,955',
 '₹ 5,955',
 '₹ 5,955',
 '₹ 5,955',
 '₹ 5,955',
 '₹ 6,375',
 '₹ 6,443',
 '₹ 6,900',
 '₹ 9,000',
 '₹ 9,429',
 '₹ 9,429',
 '₹ 11,521']

In [15]:
df=pd.DataFrame({})
df["Airline_Name"]=Company_name2
df["Departure Time"]=departure_time
df["Arrival time"]=arrivaltime
df["Departure Place"]=departureplace
df["Arrival place"]=Arrivalplace
df["Timmings"]=timmings1
df["Price"]=price1

In [16]:
df

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price
0,Go First,09:15,15:50,New Delhi,Kolkata,"06 h 35 m,1 stop via Bagdogra","₹ 5,954"
1,Spicejet,10:15,21:30,New Delhi,Kolkata,"11 h 15 m,1 stop via Guwahati","₹ 5,954"
2,Go First,19:55,04:00,New Delhi,Kolkata,"08 h 05 m,1 stop via Pune","₹ 5,954"
3,Go First,18:20,04:00,New Delhi,Kolkata,"09 h 40 m,1 stop via Pune","₹ 5,954"
4,Go First,16:35,04:00,New Delhi,Kolkata,"11 h 25 m,1 stop via Pune","₹ 5,954"
5,Go First,19:55,08:40,New Delhi,Kolkata,"12 h 45 m,1 stop via Ahmedabad","₹ 5,954"
6,Go First,16:40,08:40,New Delhi,Kolkata,"16 h,1 stop via Ahmedabad","₹ 5,954"
7,Spicejet,19:20,21:25,New Delhi,Kolkata,"26 h 05 m,1 stop via Jaipur","₹ 5,954"
8,IndiGo,07:25,13:10,New Delhi,Kolkata,"05 h 45 m,1 stop via Jaipur","₹ 5,955"
9,IndiGo,12:35,17:50,New Delhi,Kolkata,"05 h 15 m,1 stop via Lucknow","₹ 5,955"
10,IndiGo,14:40,19:50,New Delhi,Kolkata,"05 h 10 m,1 stop via Raipur","₹ 5,955"
11,IndiGo,09:15,19:50,New Delhi,Kolkata,"10 h 35 m,1 stop via Raipur","₹ 5,955"
12,IndiGo,16:05,20:15,New Delhi,Kolkata,"04 h 10 m,1 stop via Patna","₹ 5,955"
13,IndiGo,13:15,20:15,New Delhi,Kolkata,"07 h,1 stop via Patna","₹ 5,955"
14,IndiGo,16:45,22:55,New Delhi,Kolkata,"06 h 10 m,1 stop via Bhubaneswar","₹ 5,955"
15,Air India,22:00,00:05,New Delhi,Kolkata,"02 h 05 m,Non stop","₹ 6,375"
16,IndiGo,12:20,20:15,New Delhi,Kolkata,"07 h 55 m,1 stop via Patna","₹ 6,443"
17,AirAsia,08:00,19:45,New Delhi,Kolkata,"11 h 45 m,1 stop via Bengaluru","₹ 6,900"
18,Vistara,13:40,20:45,New Delhi,Kolkata,"07 h 05 m,1 stop via Lucknow","₹ 9,000"
19,"IndiGo, Vistara",15:45,20:45,New Delhi,Kolkata,"05 h,1 stop via Lucknow","₹ 9,429"
20,"Air India, Vistara",13:15,20:45,New Delhi,Kolkata,"07 h 30 m,2 stop via Gorakhpur,Lucknow","₹ 9,429"
21,Vistara,17:30,20:45,New Delhi,Kolkata,"03 h 15 m,1 stop via Lucknow","₹ 11,521"

In [17]:
dateSelect = "'2022-02-01'"

In [18]:
df['Date_of_Journey'] = dateSelect

In [19]:
df

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Date_of_Journey
0,Go First,09:15,15:50,New Delhi,Kolkata,"06 h 35 m,1 stop via Bagdogra","₹ 5,954",'2022-02-01'
1,Spicejet,10:15,21:30,New Delhi,Kolkata,"11 h 15 m,1 stop via Guwahati","₹ 5,954",'2022-02-01'
2,Go First,19:55,04:00,New Delhi,Kolkata,"08 h 05 m,1 stop via Pune","₹ 5,954",'2022-02-01'
3,Go First,18:20,04:00,New Delhi,Kolkata,"09 h 40 m,1 stop via Pune","₹ 5,954",'2022-02-01'
4,Go First,16:35,04:00,New Delhi,Kolkata,"11 h 25 m,1 stop via Pune","₹ 5,954",'2022-02-01'
5,Go First,19:55,08:40,New Delhi,Kolkata,"12 h 45 m,1 stop via Ahmedabad","₹ 5,954",'2022-02-01'
6,Go First,16:40,08:40,New Delhi,Kolkata,"16 h,1 stop via Ahmedabad","₹ 5,954",'2022-02-01'
7,Spicejet,19:20,21:25,New Delhi,Kolkata,"26 h 05 m,1 stop via Jaipur","₹ 5,954",'2022-02-01'
8,IndiGo,07:25,13:10,New Delhi,Kolkata,"05 h 45 m,1 stop via Jaipur","₹ 5,955",'2022-02-01'
9,IndiGo,12:35,17:50,New Delhi,Kolkata,"05 h 15 m,1 stop via Lucknow","₹ 5,955",'2022-02-01'
10,IndiGo,14:40,19:50,New Delhi,Kolkata,"05 h 10 m,1 stop via Raipur","₹ 5,955",'2022-02-01'
11,IndiGo,09:15,19:50,New Delhi,Kolkata,"10 h 35 m,1 stop via Raipur","₹ 5,955",'2022-02-01'
12,IndiGo,16:05,20:15,New Delhi,Kolkata,"04 h 10 m,1 stop via Patna","₹ 5,955",'2022-02-01'
13,IndiGo,13:15,20:15,New Delhi,Kolkata,"07 h,1 stop via Patna","₹ 5,955",'2022-02-01'
14,IndiGo,16:45,22:55,New Delhi,Kolkata,"06 h 10 m,1 stop via Bhubaneswar","₹ 5,955",'2022-02-01'
15,Air India,22:00,00:05,New Delhi,Kolkata,"02 h 05 m,Non stop","₹ 6,375",'2022-02-01'
16,IndiGo,12:20,20:15,New Delhi,Kolkata,"07 h 55 m,1 stop via Patna","₹ 6,443",'2022-02-01'
17,AirAsia,08:00,19:45,New Delhi,Kolkata,"11 h 45 m,1 stop via Bengaluru","₹ 6,900",'2022-02-01'
18,Vistara,13:40,20:45,New Delhi,Kolkata,"07 h 05 m,1 stop via Lucknow","₹ 9,000",'2022-02-01'
19,"IndiGo, Vistara",15:45,20:45,New Delhi,Kolkata,"05 h,1 stop via Lucknow","₹ 9,429",'2022-02-01'
20,"Air India, Vistara",13:15,20:45,New Delhi,Kolkata,"07 h 30 m,2 stop via Gorakhpur,Lucknow","₹ 9,429",'2022-02-01'
21,Vistara,17:30,20:45,New Delhi,Kolkata,"03 h 15 m,1 stop via Lucknow","₹ 11,521",'2022-02-01'

# DELHI-MUMBAI 30-01-2022

In [20]:
driver=webdriver.Chrome(r"C:\Users\Admin\Downloads\chromedriver_win32 (2)\chromedriver.exe")
url="https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-CCU-30/01/2022&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1643469080194&forwardFlowRequired=true&mpo=&intl=false"
driver.get(url)

In [21]:
for i in url:
    SCROLL_PAUSE_TIME = 1

    # Get scroll height
    """last_height = driver.execute_script("return document.body.scrollHeight")

    this dowsnt work due to floating web elements on youtube
    """

    last_height = driver.execute_script("return document.documentElement.scrollHeight")
    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0,document.documentElement.scrollHeight);")

        # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.documentElement.scrollHeight")
        if new_height == last_height:
                 break
        last_height = new_height
        
Company_name1=driver.find_elements_by_xpath('//span[@class="boldFont blackText airlineName"]')
Company_name1
Company_name2=[]

for i in Company_name1:
    Company_name2.append(i.text)
Company_name2

time1=driver.find_elements_by_xpath('//p[@class="blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter"]')
time1
time2=[]

for i in time1:
    time2.append(i.text)
time2

departure_time=[]
for i in range(0,len(time2),2):
    departure_time.append(time2[i])
departure_time

arrivaltime=[]
for i in range(1,len(time2),2):
    arrivaltime.append(time2[i])
arrivaltime

place=driver.find_elements_by_xpath('//p[@class="darkText"]')
place1=[]

for i in place:
    place1.append(i.text)
place1

departureplace=[]
for i in range(0,len(place1),2):
    departureplace.append(place1[i])
departureplace

Arrivalplace=[]
for i in range(1,len(place1),2):
    Arrivalplace.append(place1[i])
Arrivalplace

timmings=driver.find_elements_by_xpath('//div[@class="stop-info flexOne"]')
timmings
timmings1=[]

for i in timmings:
    timmings1.append(i.text.replace("\n",","))
timmings1

price=driver.find_elements_by_xpath('//div[@class="textRight flexOne"]')
price
price1=[]

for i in price:
    price1.append(i.text)
price1 


df1=pd.DataFrame({})
df1["Airline_Name"]=Company_name2
df1["Departure Time"]=departure_time
df1["Arrival time"]=arrivaltime
df1["Departure Place"]=departureplace
df1["Arrival place"]=Arrivalplace
df1["Timmings"]=timmings1
df1["Price"]=price1


dateSelect = "'2022-01-30'"

df1['Date_of_Journey'] = dateSelect

df1

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Date_of_Journey
0,Spicejet,05:15,09:05,New Delhi,Kolkata,"03 h 50 m,1 stop via Jaipur","₹ 5,954",'2022-01-30'
1,Spicejet,07:25,18:45,New Delhi,Kolkata,"11 h 20 m,1 stop via Patna","₹ 5,954",'2022-01-30'
2,Go First,17:15,08:40,New Delhi,Kolkata,"15 h 25 m,1 stop via Ahmedabad","₹ 5,954",'2022-01-30'
3,Spicejet,19:20,21:25,New Delhi,Kolkata,"26 h 05 m,1 stop via Jaipur","₹ 5,954",'2022-01-30'
4,IndiGo,14:40,19:50,New Delhi,Kolkata,"05 h 10 m,1 stop via Raipur","₹ 5,955",'2022-01-30'
5,IndiGo,09:15,19:50,New Delhi,Kolkata,"10 h 35 m,1 stop via Raipur","₹ 5,955",'2022-01-30'
6,IndiGo,15:30,20:55,New Delhi,Kolkata,"05 h 25 m,1 stop via Varanasi","₹ 5,955",'2022-01-30'
7,IndiGo,10:25,20:55,New Delhi,Kolkata,"10 h 30 m,1 stop via Varanasi","₹ 5,955",'2022-01-30'
8,IndiGo,16:45,22:55,New Delhi,Kolkata,"06 h 10 m,1 stop via Bhubaneswar","₹ 5,955",'2022-01-30'
9,IndiGo,10:55,19:40,New Delhi,Kolkata,"08 h 45 m,1 stop via Ranchi","₹ 7,420",'2022-01-30'
10,IndiGo,13:15,20:15,New Delhi,Kolkata,"07 h,1 stop via Patna","₹ 7,420",'2022-01-30'
11,IndiGo,07:25,13:10,New Delhi,Kolkata,"05 h 45 m,1 stop via Jaipur","₹ 7,908",'2022-01-30'
12,IndiGo,16:05,20:15,New Delhi,Kolkata,"04 h 10 m,1 stop via Patna","₹ 7,908",'2022-01-30'
13,IndiGo,12:20,20:15,New Delhi,Kolkata,"07 h 55 m,1 stop via Patna","₹ 8,885",'2022-01-30'
14,Vistara,13:40,20:45,New Delhi,Kolkata,"07 h 05 m,1 stop via Lucknow","₹ 9,000",'2022-01-30'
15,IndiGo,12:35,17:50,New Delhi,Kolkata,"05 h 15 m,1 stop via Lucknow","₹ 9,373",'2022-01-30'
16,"IndiGo, Vistara",15:45,20:45,New Delhi,Kolkata,"05 h,1 stop via Lucknow","₹ 9,429",'2022-01-30'
17,"Air India, Vistara",12:55,20:45,New Delhi,Kolkata,"07 h 50 m,1 stop via Lucknow","₹ 9,429",'2022-01-30'
18,"Vistara, IndiGo",13:20,20:55,New Delhi,Kolkata,"07 h 35 m,1 stop via Varanasi","₹ 9,708",'2022-01-30'
19,Go First,05:50,09:10,New Delhi,Kolkata,"03 h 20 m,1 stop via Ranchi","₹ 9,732",'2022-01-30'
20,"Air India, Vistara",13:15,20:45,New Delhi,Kolkata,"07 h 30 m,2 stop via Gorakhpur,Lucknow","₹ 9,797",'2022-01-30'
21,IndiGo,22:30,00:35,New Delhi,Kolkata,"02 h 05 m,Non stop","₹ 10,155",'2022-01-30'
22,AirAsia,08:00,19:45,New Delhi,Kolkata,"11 h 45 m,1 stop via Bengaluru","₹ 21,416",'2022-01-30'

# DELHI-MUMBAI 31-01-2022

In [24]:
driver=webdriver.Chrome(r"C:\Users\Admin\Downloads\chromedriver_win32 (2)\chromedriver.exe")
url1="https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-CCU-31/01/2022&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1643475603153&forwardFlowRequired=true&mpo=&intl=false"
driver.get(url1)

In [25]:
for i in url:
    SCROLL_PAUSE_TIME = 1

    # Get scroll height
    """last_height = driver.execute_script("return document.body.scrollHeight")

    this dowsnt work due to floating web elements on youtube
    """

    last_height = driver.execute_script("return document.documentElement.scrollHeight")
    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0,document.documentElement.scrollHeight);")

        # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.documentElement.scrollHeight")
        if new_height == last_height:
                 break
        last_height = new_height
        
Company_name1=driver.find_elements_by_xpath('//span[@class="boldFont blackText airlineName"]')
Company_name1
Company_name2=[]

for i in Company_name1:
    Company_name2.append(i.text)
Company_name2

time1=driver.find_elements_by_xpath('//p[@class="blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter"]')
time1
time2=[]

for i in time1:
    time2.append(i.text)
time2

departure_time=[]
for i in range(0,len(time2),2):
    departure_time.append(time2[i])
departure_time

arrivaltime=[]
for i in range(1,len(time2),2):
    arrivaltime.append(time2[i])
arrivaltime

place=driver.find_elements_by_xpath('//p[@class="darkText"]')
place1=[]

for i in place:
    place1.append(i.text)
place1

departureplace=[]
for i in range(0,len(place1),2):
    departureplace.append(place1[i])
departureplace

Arrivalplace=[]
for i in range(1,len(place1),2):
    Arrivalplace.append(place1[i])
Arrivalplace

timmings=driver.find_elements_by_xpath('//div[@class="stop-info flexOne"]')
timmings
timmings1=[]

for i in timmings:
    timmings1.append(i.text.replace("\n",","))
timmings1

price=driver.find_elements_by_xpath('//div[@class="textRight flexOne"]')
price
price1=[]

for i in price:
    price1.append(i.text)
price1 


df2=pd.DataFrame({})
df2["Airline_Name"]=Company_name2
df2["Departure Time"]=departure_time
df2["Arrival time"]=arrivaltime
df2["Departure Place"]=departureplace
df2["Arrival place"]=Arrivalplace
df2["Timmings"]=timmings1
df2["Price"]=price1


dateSelect = "'2022-01-31'"

df2['Date_of_Journey'] = dateSelect

df2

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Date_of_Journey
0,Spicejet,07:00,09:05,New Delhi,Kolkata,"02 h 05 m,Non stop","₹ 5,954",'2022-01-31'
1,Spicejet,09:25,14:20,New Delhi,Kolkata,"04 h 55 m,1 stop via Bagdogra","₹ 5,954",'2022-01-31'
2,,,,,,,,'2022-01-31'
3,,,,,,,,'2022-01-31'
4,,,,,,,,'2022-01-31'
5,,,,,,,,'2022-01-31'
6,,,,,,,,'2022-01-31'
7,,,,,,,,'2022-01-31'
8,,,,,,,,'2022-01-31'
9,IndiGo,18:35,20:55,New Delhi,Kolkata,"02 h 20 m,Non stop","₹ 5,955",'2022-01-31'
10,IndiGo,21:15,23:25,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 5,955",'2022-01-31'
11,IndiGo,09:50,14:10,New Delhi,Kolkata,"04 h 20 m,1 stop via Bagdogra","₹ 5,955",'2022-01-31'
12,,,,,,,,'2022-01-31'
13,,,,,,,,'2022-01-31'
14,,,,,,,,'2022-01-31'
15,,,,,,,,'2022-01-31'
16,,,,,,,,'2022-01-31'
17,,,,,,,,'2022-01-31'
18,,,,,,,,'2022-01-31'
19,Vistara,06:30,08:35,New Delhi,Kolkata,"02 h 05 m,Non stop","₹ 5,956",'2022-01-31'
20,Vistara,07:30,09:35,New Delhi,Kolkata,"02 h 05 m,Non stop","₹ 5,956",'2022-01-31'
21,Vistara,15:55,18:05,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 5,956",'2022-01-31'
22,Vistara,17:30,19:35,New Delhi,Kolkata,"02 h 05 m,Non stop","₹ 5,956",'2022-01-31'
23,Vistara,20:30,22:45,New Delhi,Kolkata,"02 h 15 m,Non stop","₹ 5,956",'2022-01-31'
24,Spicejet,20:50,23:00,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 6,060",'2022-01-31'
25,IndiGo,07:15,09:30,New Delhi,Kolkata,"02 h 15 m,Non stop","₹ 6,270",'2022-01-31'
26,IndiGo,15:10,17:20,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 6,270",'2022-01-31'
27,IndiGo,17:25,19:40,New Delhi,Kolkata,"02 h 15 m,Non stop","₹ 6,585",'2022-01-31'
28,Air India,16:55,19:10,New Delhi,Kolkata,"02 h 15 m,Non stop","₹ 6,795",'2022-01-31'
29,AirAsia,08:00,19:45,New Delhi,Kolkata,"11 h 45 m,1 stop via Bengaluru","₹ 6,900",'2022-01-31'
30,IndiGo,03:00,05:10,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 7,215",'2022-01-31'
31,IndiGo,08:40,10:50,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 7,215",'2022-01-31'
32,Air India,12:10,14:30,New Delhi,Kolkata,"02 h 20 m,Non stop","₹ 7,635",'2022-01-31'
33,IndiGo,10:00,12:10,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 9,105",'2022-01-31'
34,"Spicejet, IndiGo",12:15,20:55,New Delhi,Kolkata,"08 h 40 m,1 stop via Varanasi","₹ 9,707",'2022-01-31'
35,,,,,,,,'2022-01-31'
36,,,,,,,,'2022-01-31'
37,,,,,,,,'2022-01-31'
38,,,,,,,,'2022-01-31'

# DELHI-MUMBAI 07-02-2022

In [26]:
driver=webdriver.Chrome(r"C:\Users\Admin\Downloads\chromedriver_win32 (2)\chromedriver.exe")
url1="https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-CCU-07/02/2022&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1643475901323&forwardFlowRequired=true&mpo=&intl=false"
driver.get(url1)

In [27]:
for i in url:
    SCROLL_PAUSE_TIME = 1

    # Get scroll height
    """last_height = driver.execute_script("return document.body.scrollHeight")

    this dowsnt work due to floating web elements on youtube
    """

    last_height = driver.execute_script("return document.documentElement.scrollHeight")
    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0,document.documentElement.scrollHeight);")

        # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.documentElement.scrollHeight")
        if new_height == last_height:
                 break
        last_height = new_height
        
Company_name1=driver.find_elements_by_xpath('//span[@class="boldFont blackText airlineName"]')
Company_name1
Company_name2=[]

for i in Company_name1:
    Company_name2.append(i.text)
Company_name2

time1=driver.find_elements_by_xpath('//p[@class="blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter"]')
time1
time2=[]

for i in time1:
    time2.append(i.text)
time2

departure_time=[]
for i in range(0,len(time2),2):
    departure_time.append(time2[i])
departure_time

arrivaltime=[]
for i in range(1,len(time2),2):
    arrivaltime.append(time2[i])
arrivaltime

place=driver.find_elements_by_xpath('//p[@class="darkText"]')
place1=[]

for i in place:
    place1.append(i.text)
place1

departureplace=[]
for i in range(0,len(place1),2):
    departureplace.append(place1[i])
departureplace

Arrivalplace=[]
for i in range(1,len(place1),2):
    Arrivalplace.append(place1[i])
Arrivalplace

timmings=driver.find_elements_by_xpath('//div[@class="stop-info flexOne"]')
timmings
timmings1=[]

for i in timmings:
    timmings1.append(i.text.replace("\n",","))
timmings1

price=driver.find_elements_by_xpath('//div[@class="textRight flexOne"]')
price
price1=[]

for i in price:
    price1.append(i.text)
price1 


df3=pd.DataFrame({})
df3["Airline_Name"]=Company_name2
df3["Departure Time"]=departure_time
df3["Arrival time"]=arrivaltime
df3["Departure Place"]=departureplace
df3["Arrival place"]=Arrivalplace
df3["Timmings"]=timmings1
df3["Price"]=price1


dateSelect = "'2022-02-07'"

df3['Date_of_Journey'] = dateSelect

df3

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Date_of_Journey
0,Go First,05:50,08:00,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 5,954",'2022-02-07'
1,Spicejet,07:00,09:05,New Delhi,Kolkata,"02 h 05 m,Non stop","₹ 5,954",'2022-02-07'
2,Go First,19:25,21:45,New Delhi,Kolkata,"02 h 20 m,Non stop","₹ 5,954",'2022-02-07'
3,Spicejet,20:50,23:00,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 5,954",'2022-02-07'
4,Go First,07:20,12:30,New Delhi,Kolkata,"05 h 10 m,1 stop via Hyderabad","₹ 5,954",'2022-02-07'
5,,,,,,,,'2022-02-07'
6,,,,,,,,'2022-02-07'
7,,,,,,,,'2022-02-07'
8,,,,,,,,'2022-02-07'
9,,,,,,,,'2022-02-07'
10,,,,,,,,'2022-02-07'
11,,,,,,,,'2022-02-07'
12,,,,,,,,'2022-02-07'
13,,,,,,,,'2022-02-07'
14,,,,,,,,'2022-02-07'
15,,,,,,,,'2022-02-07'
16,,,,,,,,'2022-02-07'
17,,,,,,,,'2022-02-07'
18,,,,,,,,'2022-02-07'
19,IndiGo,05:55,08:10,New Delhi,Kolkata,"02 h 15 m,Non stop","₹ 5,955",'2022-02-07'
20,Air India,06:50,09:00,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 5,955",'2022-02-07'
21,IndiGo,07:15,09:30,New Delhi,Kolkata,"02 h 15 m,Non stop","₹ 5,955",'2022-02-07'
22,IndiGo,08:40,10:50,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 5,955",'2022-02-07'
23,IndiGo,15:10,17:20,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 5,955",'2022-02-07'
24,Air India,16:55,19:10,New Delhi,Kolkata,"02 h 15 m,Non stop","₹ 5,955",'2022-02-07'
25,IndiGo,17:25,19:40,New Delhi,Kolkata,"02 h 15 m,Non stop","₹ 5,955",'2022-02-07'
26,IndiGo,18:35,20:55,New Delhi,Kolkata,"02 h 20 m,Non stop","₹ 5,955",'2022-02-07'
27,IndiGo,21:15,23:25,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 5,955",'2022-02-07'
28,IndiGo,12:35,17:50,New Delhi,Kolkata,"05 h 15 m,1 stop via Lucknow","₹ 5,955",'2022-02-07'
29,,,,,,,,'2022-02-07'
30,,,,,,,,'2022-02-07'
31,,,,,,,,'2022-02-07'
32,,,,,,,,'2022-02-07'
33,Vistara,06:30,08:35,New Delhi,Kolkata,"02 h 05 m,Non stop","₹ 5,956",'2022-02-07'
34,Vistara,07:30,09:35,New Delhi,Kolkata,"02 h 05 m,Non stop","₹ 5,956",'2022-02-07'
35,AirAsia,08:00,19:45,New Delhi,Kolkata,"11 h 45 m,1 stop via Bengaluru","₹ 6,254",'2022-02-07'
36,Air India,12:10,14:30,New Delhi,Kolkata,"02 h 20 m,Non stop","₹ 6,375",'2022-02-07'
37,Go First,19:35,07:55,New Delhi,Kolkata,"12 h 20 m,1 stop via Hyderabad","₹ 6,461",'2022-02-07'
38,IndiGo,10:00,12:10,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 6,585",'2022-02-07'
39,IndiGo,03:00,05:10,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 6,900",'2022-02-07'
40,IndiGo,05:50,14:35,New Delhi,Kolkata,"08 h 45 m,1 stop via Bhubaneswar","₹ 6,932",'2022-02-07'
41,Vistara,17:30,19:35,New Delhi,Kolkata,"02 h 05 m,Non stop","₹ 8,791",'2022-02-07'
42,IndiGo,09:50,15:20,New Delhi,Kolkata,"05 h 30 m,1 stop via Bagdogra","₹ 9,373",'2022-02-07'

# DELHI-MUMBAI 14-02-2022

In [28]:
driver=webdriver.Chrome(r"C:\Users\Admin\Downloads\chromedriver_win32 (2)\chromedriver.exe")
url1="https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-CCU-14/02/2022&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1643476296597&forwardFlowRequired=true&mpo=&intl=false"
driver.get(url1)

In [29]:
for i in url:
    SCROLL_PAUSE_TIME = 1

    # Get scroll height
    """last_height = driver.execute_script("return document.body.scrollHeight")

    this dowsnt work due to floating web elements on youtube
    """

    last_height = driver.execute_script("return document.documentElement.scrollHeight")
    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0,document.documentElement.scrollHeight);")

        # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.documentElement.scrollHeight")
        if new_height == last_height:
                 break
        last_height = new_height
        
Company_name1=driver.find_elements_by_xpath('//span[@class="boldFont blackText airlineName"]')
Company_name1
Company_name2=[]

for i in Company_name1:
    Company_name2.append(i.text)
Company_name2

time1=driver.find_elements_by_xpath('//p[@class="blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter"]')
time1
time2=[]

for i in time1:
    time2.append(i.text)
time2

departure_time=[]
for i in range(0,len(time2),2):
    departure_time.append(time2[i])
departure_time

arrivaltime=[]
for i in range(1,len(time2),2):
    arrivaltime.append(time2[i])
arrivaltime

place=driver.find_elements_by_xpath('//p[@class="darkText"]')
place1=[]

for i in place:
    place1.append(i.text)
place1

departureplace=[]
for i in range(0,len(place1),2):
    departureplace.append(place1[i])
departureplace

Arrivalplace=[]
for i in range(1,len(place1),2):
    Arrivalplace.append(place1[i])
Arrivalplace

timmings=driver.find_elements_by_xpath('//div[@class="stop-info flexOne"]')
timmings
timmings1=[]

for i in timmings:
    timmings1.append(i.text.replace("\n",","))
timmings1

price=driver.find_elements_by_xpath('//div[@class="textRight flexOne"]')
price
price1=[]

for i in price:
    price1.append(i.text)
price1 


df4=pd.DataFrame({})
df4["Airline_Name"]=Company_name2
df4["Departure Time"]=departure_time
df4["Arrival time"]=arrivaltime
df4["Departure Place"]=departureplace
df4["Arrival place"]=Arrivalplace
df4["Timmings"]=timmings1
df4["Price"]=price1


dateSelect = "'2022-02-14'"

df4['Date_of_Journey'] = dateSelect

df4

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Date_of_Journey
0,Go First,05:50,08:00,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 2,480",'2022-02-14'
1,IndiGo,05:55,08:10,New Delhi,Kolkata,"02 h 15 m,Non stop","₹ 2,480",'2022-02-14'
2,Go First,19:25,21:45,New Delhi,Kolkata,"02 h 20 m,Non stop","₹ 2,480",'2022-02-14'
3,AirAsia,06:20,12:00,New Delhi,Kolkata,"05 h 40 m,1 stop via Bagdogra","₹ 2,480",'2022-02-14'
4,,,,,,,,'2022-02-14'
5,,,,,,,,'2022-02-14'
6,,,,,,,,'2022-02-14'
7,,,,,,,,'2022-02-14'
8,,,,,,,,'2022-02-14'
9,AirAsia,04:45,07:10,New Delhi,Kolkata,"02 h 25 m,Non stop","₹ 2,481",'2022-02-14'
10,Spicejet,07:00,09:05,New Delhi,Kolkata,"02 h 05 m,Non stop","₹ 2,481",'2022-02-14'
11,AirAsia,16:50,19:30,New Delhi,Kolkata,"02 h 40 m,Non stop","₹ 2,481",'2022-02-14'
12,Spicejet,20:50,23:00,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 2,481",'2022-02-14'
13,AirAsia,21:00,23:10,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 2,481",'2022-02-14'
14,Air India,06:50,09:00,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 2,482",'2022-02-14'
15,Air India,16:55,19:10,New Delhi,Kolkata,"02 h 15 m,Non stop","₹ 2,482",'2022-02-14'
16,Vistara,06:30,08:35,New Delhi,Kolkata,"02 h 05 m,Non stop","₹ 2,483",'2022-02-14'
17,Vistara,07:30,09:35,New Delhi,Kolkata,"02 h 05 m,Non stop","₹ 2,693",'2022-02-14'
18,Go First,21:00,08:40,New Delhi,Kolkata,"11 h 40 m,1 stop via Lucknow","₹ 3,087",'2022-02-14'
19,IndiGo,07:15,09:30,New Delhi,Kolkata,"02 h 15 m,Non stop","₹ 3,482",'2022-02-14'
20,IndiGo,18:35,20:55,New Delhi,Kolkata,"02 h 20 m,Non stop","₹ 3,482",'2022-02-14'
21,IndiGo,21:15,23:25,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 3,482",'2022-02-14'
22,AirAsia,15:25,23:10,New Delhi,Kolkata,"07 h 45 m,2 stop via Pune,Bhubaneswar","₹ 3,483",'2022-02-14'
23,,,,,,,,'2022-02-14'
24,,,,,,,,'2022-02-14'
25,,,,,,,,'2022-02-14'
26,,,,,,,,'2022-02-14'
27,,,,,,,,'2022-02-14'
28,,,,,,,,'2022-02-14'
29,,,,,,,,'2022-02-14'
30,,,,,,,,'2022-02-14'
31,Air India,12:10,14:30,New Delhi,Kolkata,"02 h 20 m,Non stop","₹ 4,097",'2022-02-14'
32,Spicejet,10:15,21:30,New Delhi,Kolkata,"11 h 15 m,1 stop via Guwahati","₹ 4,174",'2022-02-14'
33,,,,,,,,'2022-02-14'
34,,,,,,,,'2022-02-14'
35,,,,,,,,'2022-02-14'
36,,,,,,,,'2022-02-14'
37,IndiGo,03:00,05:10,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 4,485",'2022-02-14'
38,IndiGo,08:40,10:50,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 4,485",'2022-02-14'
39,IndiGo,10:00,12:10,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 4,485",'2022-02-14'
40,IndiGo,15:10,17:20,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 4,485",'2022-02-14'
41,IndiGo,17:25,19:40,New Delhi,Kolkata,"02 h 15 m,Non stop","₹ 4,485",'2022-02-14'
42,Go First,17:00,23:35,New Delhi,Kolkata,"06 h 35 m,1 stop via Mumbai","₹ 4,730",'2022-02-14'
43,,,,,,,,'2022-02-14'
44,,,,,,,,'2022-02-14'
45,,,,,,,,'2022-02-14'
46,,,,,,,,'2022-02-14'
47,,,,,,,,'2022-02-14'
48,,,,,,,,'2022-02-14'
49,,,,,,,,'2022-02-14'
50,,,,,,,,'2022-02-14'
51,,,,,,,,'2022-02-14'
52,,,,,,,,'2022-02-14'
53,,,,,,,,'2022-02-14'
54,,,,,,,,'2022-02-14'
55,Vistara,17:30,19:35,New Delhi,Kolkata,"02 h 05 m,Non stop","₹ 9,526",'2022-02-14'
56,Air India,04:50,12:30,New Delhi,Kolkata,"07 h 40 m,2 stop via Surat,Bhubaneswar","₹ 15,720",'2022-02-14'

# DELHI-MUMBAI 21-02-2022

In [30]:
driver=webdriver.Chrome(r"C:\Users\Admin\Downloads\chromedriver_win32 (2)\chromedriver.exe")
url1="https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-CCU-21/02/2022&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1643476357652&forwardFlowRequired=true&mpo=&intl=false"
driver.get(url1)

In [31]:
for i in url:
    SCROLL_PAUSE_TIME = 1

    # Get scroll height
    """last_height = driver.execute_script("return document.body.scrollHeight")

    this dowsnt work due to floating web elements on youtube
    """

    last_height = driver.execute_script("return document.documentElement.scrollHeight")
    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0,document.documentElement.scrollHeight);")

        # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.documentElement.scrollHeight")
        if new_height == last_height:
                 break
        last_height = new_height
        
Company_name1=driver.find_elements_by_xpath('//span[@class="boldFont blackText airlineName"]')
Company_name1
Company_name2=[]

for i in Company_name1:
    Company_name2.append(i.text)
Company_name2

time1=driver.find_elements_by_xpath('//p[@class="blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter"]')
time1
time2=[]

for i in time1:
    time2.append(i.text)
time2

departure_time=[]
for i in range(0,len(time2),2):
    departure_time.append(time2[i])
departure_time

arrivaltime=[]
for i in range(1,len(time2),2):
    arrivaltime.append(time2[i])
arrivaltime

place=driver.find_elements_by_xpath('//p[@class="darkText"]')
place1=[]

for i in place:
    place1.append(i.text)
place1

departureplace=[]
for i in range(0,len(place1),2):
    departureplace.append(place1[i])
departureplace

Arrivalplace=[]
for i in range(1,len(place1),2):
    Arrivalplace.append(place1[i])
Arrivalplace

timmings=driver.find_elements_by_xpath('//div[@class="stop-info flexOne"]')
timmings
timmings1=[]

for i in timmings:
    timmings1.append(i.text.replace("\n",","))
timmings1

price=driver.find_elements_by_xpath('//div[@class="textRight flexOne"]')
price
price1=[]

for i in price:
    price1.append(i.text)
price1 


df5=pd.DataFrame({})
df5["Airline_Name"]=Company_name2
df5["Departure Time"]=departure_time
df5["Arrival time"]=arrivaltime
df5["Departure Place"]=departureplace
df5["Arrival place"]=Arrivalplace
df5["Timmings"]=timmings1
df5["Price"]=price1


dateSelect = "'2022-02-21'"

df5['Date_of_Journey'] = dateSelect

df5

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Date_of_Journey
0,Go First,05:50,08:00,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 2,480",'2022-02-21'
1,IndiGo,05:55,08:10,New Delhi,Kolkata,"02 h 15 m,Non stop","₹ 2,480",'2022-02-21'
2,IndiGo,07:15,09:30,New Delhi,Kolkata,"02 h 15 m,Non stop","₹ 2,480",'2022-02-21'
3,IndiGo,08:40,10:50,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 2,480",'2022-02-21'
4,IndiGo,10:00,12:10,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 2,480",'2022-02-21'
5,IndiGo,15:10,17:20,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 2,480",'2022-02-21'
6,IndiGo,17:25,19:40,New Delhi,Kolkata,"02 h 15 m,Non stop","₹ 2,480",'2022-02-21'
7,IndiGo,18:35,20:55,New Delhi,Kolkata,"02 h 20 m,Non stop","₹ 2,480",'2022-02-21'
8,Go First,19:25,21:45,New Delhi,Kolkata,"02 h 20 m,Non stop","₹ 2,480",'2022-02-21'
9,IndiGo,19:45,21:55,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 2,480",'2022-02-21'
10,IndiGo,21:15,23:25,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 2,480",'2022-02-21'
11,AirAsia,07:10,15:25,New Delhi,Kolkata,"08 h 15 m,2 stop via Guwahati,Imphal","₹ 2,480",'2022-02-21'
12,,,,,,,,'2022-02-21'
13,,,,,,,,'2022-02-21'
14,,,,,,,,'2022-02-21'
15,,,,,,,,'2022-02-21'
16,AirAsia,04:45,07:10,New Delhi,Kolkata,"02 h 25 m,Non stop","₹ 2,481",'2022-02-21'
17,Spicejet,07:00,09:05,New Delhi,Kolkata,"02 h 05 m,Non stop","₹ 2,481",'2022-02-21'
18,AirAsia,16:50,19:30,New Delhi,Kolkata,"02 h 40 m,Non stop","₹ 2,481",'2022-02-21'
19,Spicejet,20:50,23:00,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 2,481",'2022-02-21'
20,AirAsia,21:00,23:10,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 2,481",'2022-02-21'
21,Air India,06:50,09:00,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 2,482",'2022-02-21'
22,Air India,16:55,19:10,New Delhi,Kolkata,"02 h 15 m,Non stop","₹ 2,482",'2022-02-21'
23,Air India,04:50,12:30,New Delhi,Kolkata,"07 h 40 m,2 stop via Surat,Bhubaneswar","₹ 2,482",'2022-02-21'
24,Vistara,06:30,08:35,New Delhi,Kolkata,"02 h 05 m,Non stop","₹ 2,483",'2022-02-21'
25,Vistara,07:30,09:35,New Delhi,Kolkata,"02 h 05 m,Non stop","₹ 2,483",'2022-02-21'
26,Vistara,15:55,18:05,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 2,483",'2022-02-21'
27,Vistara,17:30,19:35,New Delhi,Kolkata,"02 h 05 m,Non stop","₹ 2,483",'2022-02-21'
28,Vistara,20:30,22:45,New Delhi,Kolkata,"02 h 15 m,Non stop","₹ 2,483",'2022-02-21'
29,IndiGo,07:50,17:50,New Delhi,Kolkata,"10 h,1 stop via Lucknow","₹ 2,823",'2022-02-21'
30,,,,,,,,'2022-02-21'
31,,,,,,,,'2022-02-21'
32,,,,,,,,'2022-02-21'
33,Air India,12:10,14:30,New Delhi,Kolkata,"02 h 20 m,Non stop","₹ 3,428",'2022-02-21'
34,IndiGo,03:00,05:10,New Delhi,Kolkata,"02 h 10 m,Non stop","₹ 3,482",'2022-02-21'
35,AirAsia,15:25,23:10,New Delhi,Kolkata,"07 h 45 m,2 stop via Pune,Bhubaneswar","₹ 3,483",'2022-02-21'
36,,,,,,,,'2022-02-21'
37,,,,,,,,'2022-02-21'
38,,,,,,,,'2022-02-21'
39,,,,,,,,'2022-02-21'
40,,,,,,,,'2022-02-21'
41,,,,,,,,'2022-02-21'
42,,,,,,,,'2022-02-21'
43,,,,,,,,'2022-02-21'
44,,,,,,,,'2022-02-21'
45,,,,,,,,'2022-02-21'
46,,,,,,,,'2022-02-21'
47,,,,,,,,'2022-02-21'
48,,,,,,,,'2022-02-21'
49,,,,,,,,'2022-02-21'
50,,,,,,,,'2022-02-21'
51,,,,,,,,'2022-02-21'
52,,,,,,,,'2022-02-21'
53,,,,,,,,'2022-02-21'
54,,,,,,,,'2022-02-21'
55,,,,,,,,'2022-02-21'
56,,,,,,,,'2022-02-21'
57,,,,,,,,'2022-02-21'
58,,,,,,,,'2022-02-21'

In [32]:
# append method
df6= df.append([df1,df2,df3,df4,df5])
df6

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Date_of_Journey
0,Go First,09:15,15:50,New Delhi,Kolkata,"06 h 35 m,1 stop via Bagdogra","₹ 5,954",'2022-02-01'
1,Spicejet,10:15,21:30,New Delhi,Kolkata,"11 h 15 m,1 stop via Guwahati","₹ 5,954",'2022-02-01'
2,Go First,19:55,04:00,New Delhi,Kolkata,"08 h 05 m,1 stop via Pune","₹ 5,954",'2022-02-01'
3,Go First,18:20,04:00,New Delhi,Kolkata,"09 h 40 m,1 stop via Pune","₹ 5,954",'2022-02-01'
4,Go First,16:35,04:00,New Delhi,Kolkata,"11 h 25 m,1 stop via Pune","₹ 5,954",'2022-02-01'
...,...,...,...,...,...,...,...,...
54,,,,,,,,'2022-02-21'
55,,,,,,,,'2022-02-21'
56,,,,,,,,'2022-02-21'
57,,,,,,,,'2022-02-21'
58,,,,,,,,'2022-02-21'

In [33]:
file_name='DELHI-KOLKATTA_FLIGHT.xlsx'
df6.to_excel(file_name)
print('DataFrame is written to Excel File successfully')

DataFrame is written to Excel File successfully