# MUMBAI-BANGALORE

In [1]:
!pip install selenium
!pip install undetected-chromedriver
     

import time
import warnings
warnings.filterwarnings('ignore')

Requirement already satisfied: selenium in c:\users\admin\anaconda3\lib\site-packages (3.141.0)
Requirement already satisfied: urllib3 in c:\users\admin\anaconda3\lib\site-packages (from selenium) (1.25.11)
Requirement already satisfied: undetected-chromedriver in c:\users\admin\anaconda3\lib\site-packages (3.0.6)
Requirement already satisfied: websockets in c:\users\admin\anaconda3\lib\site-packages (from undetected-chromedriver) (10.1)
Requirement already satisfied: selenium in c:\users\admin\anaconda3\lib\site-packages (from undetected-chromedriver) (3.141.0)
Requirement already satisfied: requests in c:\users\admin\anaconda3\lib\site-packages (from undetected-chromedriver) (2.24.0)
Requirement already satisfied: urllib3 in c:\users\admin\anaconda3\lib\site-packages (from selenium->undetected-chromedriver) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\anaconda3\lib\site-packages (from requests->undetected-chromedriver) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from requests->undetected-chromedriver) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\admin\anaconda3\lib\site-packages (from requests->undetected-chromedriver) (3.0.4)

In [2]:
import selenium
import pandas as pd
from selenium import webdriver 
from selenium.common.exceptions import  StaleElementReferenceException,ElementClickInterceptedException
from selenium.common.exceptions import  NoSuchElementException,NoSuchWindowException

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

# MUMBAI-BANGALORE 31-01-2022

In [3]:
driver=webdriver.Chrome(r"C:\Users\Admin\Downloads\chromedriver_win32 (2)\chromedriver.exe")
url="https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=31%2F01%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=1114255767458&version=1.1&viewName=normal"
driver.get(url)

In [4]:
for i in url:
    SCROLL_PAUSE_TIME = 1

    # Get scroll height
    """last_height = driver.execute_script("return document.body.scrollHeight")

    this dowsnt work due to floating web elements on youtube
    """

    last_height = driver.execute_script("return document.documentElement.scrollHeight")
    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0,document.documentElement.scrollHeight);")

        # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.documentElement.scrollHeight")
        if new_height == last_height:
                 break
        last_height = new_height
        
Company_name1=driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
Company_name1
Company_name2=[]

for i in Company_name1:
    Company_name2.append(i.text)
Company_name2


Departuretime=driver.find_elements_by_xpath('//div[@class="fs-15 bold time"]')
Departuretime
Departuretime1=[]

for i in Departuretime:
    Departuretime1.append(i.text)
Departuretime1


arrivaltime=driver.find_elements_by_xpath('//p[@class="bold fs-15 mb-2 pr time"]')
arrivaltime
arrivaltime1=[]

for i in arrivaltime:
    arrivaltime1.append(i.text)
arrivaltime1

place=driver.find_elements_by_xpath('//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
place
place1=[]

for i in place:
    place1.append(i.text)
place1

departureplace=[]
for i in range(0,len(place1),2):
    departureplace.append(place1[i])
departureplace

Arrivalplace=[]
for i in range(1,len(place1),2):
    Arrivalplace.append(place1[i])
Arrivalplace

timmings=driver.find_elements_by_xpath('//p[@class="fs-12 bold du mb-2"]')
timmings
timmings1=[]

for i in timmings:
    timmings1.append(i.text)
timmings1    

price=driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
price
price1=[]

for i in price:
    price1.append(i.text)
price1   

stoppage=driver.find_elements_by_xpath('//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
stoppage
stoppage1=[]

for i in stoppage:
    stoppage1.append(i.text)
stoppage1  

dateSelect = "'2022-01-31'"

df1=pd.DataFrame({})
df1["Airline_Name"]=Company_name2
df1["Departure Time"]=Departuretime1
df1["Arrival time"]=arrivaltime1
df1["Departure Place"]=departureplace
df1["Arrival place"]=Arrivalplace
df1["Timmings"]=timmings1
df1["Price"]=price1
df1["Stoppages"]=stoppage1
df1['Date_of_Journey'] = dateSelect

df1

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Stoppages,Date_of_Journey
0,Go First,20:35,22:20,Mumbai,Bangalore,1h 45m,"5,102",Non Stop,'2022-01-31'
1,Go First,05:25,10:25,Mumbai,Bangalore,5h 00m,"5,102",1 Stop,'2022-01-31'
2,Go First,13:30,21:25,Mumbai,Bangalore,7h 55m,"5,102",1 Stop,'2022-01-31'
3,Go First,19:15,10:20\n+ 1 day,Mumbai,Bangalore,15h 05m,"5,102",1 Stop,'2022-01-31'
4,SpiceJet,15:30,09:00\n+ 1 day,Mumbai,Bangalore,17h 30m,"5,102",1 Stop,'2022-01-31'
...,...,...,...,...,...,...,...,...,...
85,Air India,12:00,00:10\n+ 2 days,Mumbai,Bangalore,36h 10m,"14,766",2 Stop(s),'2022-01-31'
86,Air India,20:55,01:50\n+ 2 days,Mumbai,Bangalore,28h 55m,"16,023",1 Stop,'2022-01-31'
87,Air India,21:30,21:45\n+ 1 day,Mumbai,Bangalore,24h 15m,"16,236",2 Stop(s),'2022-01-31'
88,Vistara,12:15,10:50\n+ 1 day,Mumbai,Bangalore,22h 35m,"16,916",2 Stop(s),'2022-01-31'
89,Vistara,12:15,23:20,Mumbai,Bangalore,11h 05m,"17,021",2 Stop(s),'2022-01-31'

# MUMBAI-BANGALORE 01-02-2022

In [5]:
driver=webdriver.Chrome(r"C:\Users\Admin\Downloads\chromedriver_win32 (2)\chromedriver.exe")
url1="https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=01%2F02%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=1211484160060&version=1.1&viewName=normal"
driver.get(url1)

In [6]:
for i in url:
    SCROLL_PAUSE_TIME = 1

    # Get scroll height
    """last_height = driver.execute_script("return document.body.scrollHeight")

    this dowsnt work due to floating web elements on youtube
    """

    last_height = driver.execute_script("return document.documentElement.scrollHeight")
    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0,document.documentElement.scrollHeight);")

        # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.documentElement.scrollHeight")
        if new_height == last_height:
                 break
        last_height = new_height
        
Company_name1=driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
Company_name1
Company_name2=[]

for i in Company_name1:
    Company_name2.append(i.text)
Company_name2


Departuretime=driver.find_elements_by_xpath('//div[@class="fs-15 bold time"]')
Departuretime
Departuretime1=[]

for i in Departuretime:
    Departuretime1.append(i.text)
Departuretime1


arrivaltime=driver.find_elements_by_xpath('//p[@class="bold fs-15 mb-2 pr time"]')
arrivaltime
arrivaltime1=[]

for i in arrivaltime:
    arrivaltime1.append(i.text)
arrivaltime1

place=driver.find_elements_by_xpath('//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
place
place1=[]

for i in place:
    place1.append(i.text)
place1

departureplace=[]
for i in range(0,len(place1),2):
    departureplace.append(place1[i])
departureplace

Arrivalplace=[]
for i in range(1,len(place1),2):
    Arrivalplace.append(place1[i])
Arrivalplace

timmings=driver.find_elements_by_xpath('//p[@class="fs-12 bold du mb-2"]')
timmings
timmings1=[]

for i in timmings:
    timmings1.append(i.text)
timmings1    

price=driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
price
price1=[]

for i in price:
    price1.append(i.text)
price1   

stoppage=driver.find_elements_by_xpath('//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
stoppage
stoppage1=[]

for i in stoppage:
    stoppage1.append(i.text)
stoppage1  

dateSelect = "'2022-02-01'"

df2=pd.DataFrame({})
df2["Airline_Name"]=Company_name2
df2["Departure Time"]=Departuretime1
df2["Arrival time"]=arrivaltime1
df2["Departure Place"]=departureplace
df2["Arrival place"]=Arrivalplace
df2["Timmings"]=timmings1
df2["Price"]=price1
df2["Stoppages"]=stoppage1
df2['Date_of_Journey'] = dateSelect

df2

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Stoppages,Date_of_Journey
0,Go First,06:05,07:40,Mumbai,Bangalore,1h 35m,"5,102",Non Stop,'2022-02-01'
1,Go First,21:00,22:45,Mumbai,Bangalore,1h 45m,"5,102",Non Stop,'2022-02-01'
2,Go First,19:15,23:40,Mumbai,Bangalore,4h 25m,"5,102",1 Stop,'2022-02-01'
3,Go First,05:20,10:20,Mumbai,Bangalore,5h 00m,"5,102",1 Stop,'2022-02-01'
4,Go First,21:15,08:40\n+ 1 day,Mumbai,Bangalore,11h 25m,"5,102",1 Stop,'2022-02-01'
...,...,...,...,...,...,...,...,...,...
88,Air India,12:00,08:55\n+ 1 day,Mumbai,Bangalore,20h 55m,"14,766",2 Stop(s),'2022-02-01'
89,Air India,12:00,12:30\n+ 1 day,Mumbai,Bangalore,24h 30m,"14,766",2 Stop(s),'2022-02-01'
90,Air India,12:00,16:15\n+ 1 day,Mumbai,Bangalore,28h 15m,"14,766",2 Stop(s),'2022-02-01'
91,Air India,08:45,16:15\n+ 1 day,Mumbai,Bangalore,31h 30m,"14,766",3 Stop(s),'2022-02-01'
92,Air India,12:00,20:05\n+ 1 day,Mumbai,Bangalore,32h 05m,"14,766",2 Stop(s),'2022-02-01'

# MUMBAI-BANGALORE 07-02-2022

In [7]:
driver=webdriver.Chrome(r"C:\Users\Admin\Downloads\chromedriver_win32 (2)\chromedriver.exe")
url1="https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=07%2F02%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=1389553713331&version=1.1&viewName=normal"
driver.get(url1)

In [8]:
for i in url:
    SCROLL_PAUSE_TIME = 1

    # Get scroll height
    """last_height = driver.execute_script("return document.body.scrollHeight")

    this dowsnt work due to floating web elements on youtube
    """

    last_height = driver.execute_script("return document.documentElement.scrollHeight")
    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0,document.documentElement.scrollHeight);")

        # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.documentElement.scrollHeight")
        if new_height == last_height:
                 break
        last_height = new_height
        
Company_name1=driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
Company_name1
Company_name2=[]

for i in Company_name1:
    Company_name2.append(i.text)
Company_name2


Departuretime=driver.find_elements_by_xpath('//div[@class="fs-15 bold time"]')
Departuretime
Departuretime1=[]

for i in Departuretime:
    Departuretime1.append(i.text)
Departuretime1


arrivaltime=driver.find_elements_by_xpath('//p[@class="bold fs-15 mb-2 pr time"]')
arrivaltime
arrivaltime1=[]

for i in arrivaltime:
    arrivaltime1.append(i.text)
arrivaltime1

place=driver.find_elements_by_xpath('//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
place
place1=[]

for i in place:
    place1.append(i.text)
place1

departureplace=[]
for i in range(0,len(place1),2):
    departureplace.append(place1[i])
departureplace

Arrivalplace=[]
for i in range(1,len(place1),2):
    Arrivalplace.append(place1[i])
Arrivalplace

timmings=driver.find_elements_by_xpath('//p[@class="fs-12 bold du mb-2"]')
timmings
timmings1=[]

for i in timmings:
    timmings1.append(i.text)
timmings1    

price=driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
price
price1=[]

for i in price:
    price1.append(i.text)
price1   

stoppage=driver.find_elements_by_xpath('//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
stoppage
stoppage1=[]

for i in stoppage:
    stoppage1.append(i.text)
stoppage1  

dateSelect = "'2022-02-07'"

df3=pd.DataFrame({})
df3["Airline_Name"]=Company_name2
df3["Departure Time"]=Departuretime1
df3["Arrival time"]=arrivaltime1
df3["Departure Place"]=departureplace
df3["Arrival place"]=Arrivalplace
df3["Timmings"]=timmings1
df3["Price"]=price1
df3["Stoppages"]=stoppage1
df3['Date_of_Journey'] = dateSelect

df3

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Stoppages,Date_of_Journey
0,Go First,06:05,07:40,Mumbai,Bangalore,1h 35m,"5,102",Non Stop,'2022-02-07'
1,Go First,14:35,16:10,Mumbai,Bangalore,1h 35m,"5,102",Non Stop,'2022-02-07'
2,Go First,21:00,22:45,Mumbai,Bangalore,1h 45m,"5,102",Non Stop,'2022-02-07'
3,Go First,11:30,15:10,Mumbai,Bangalore,3h 40m,"5,102",1 Stop,'2022-02-07'
4,Go First,19:15,23:40,Mumbai,Bangalore,4h 25m,"5,102",1 Stop,'2022-02-07'
...,...,...,...,...,...,...,...,...,...
103,Air India,08:10,08:55\n+ 1 day,Mumbai,Bangalore,24h 45m,"14,766",2 Stop(s),'2022-02-07'
104,Air India,08:10,12:15\n+ 1 day,Mumbai,Bangalore,28h 05m,"14,766",2 Stop(s),'2022-02-07'
105,Air India,12:00,20:05\n+ 1 day,Mumbai,Bangalore,32h 05m,"14,766",2 Stop(s),'2022-02-07'
106,Vistara,16:05,18:15\n+ 1 day,Mumbai,Bangalore,26h 10m,"16,233",1 Stop,'2022-02-07'
107,Vistara,16:05,20:25\n+ 1 day,Mumbai,Bangalore,28h 20m,"16,662",2 Stop(s),'2022-02-07'

# MUMBAI-BANGALORE 14-02-2022

In [9]:
driver=webdriver.Chrome(r"C:\Users\Admin\Downloads\chromedriver_win32 (2)\chromedriver.exe")
url1="https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=14%2F02%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=179208340301&version=1.1&viewName=normal"
driver.get(url1)

In [10]:
for i in url:
    SCROLL_PAUSE_TIME = 1

    # Get scroll height
    """last_height = driver.execute_script("return document.body.scrollHeight")

    this dowsnt work due to floating web elements on youtube
    """

    last_height = driver.execute_script("return document.documentElement.scrollHeight")
    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0,document.documentElement.scrollHeight);")

        # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.documentElement.scrollHeight")
        if new_height == last_height:
                 break
        last_height = new_height
        
Company_name1=driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
Company_name1
Company_name2=[]

for i in Company_name1:
    Company_name2.append(i.text)
Company_name2


Departuretime=driver.find_elements_by_xpath('//div[@class="fs-15 bold time"]')
Departuretime
Departuretime1=[]

for i in Departuretime:
    Departuretime1.append(i.text)
Departuretime1


arrivaltime=driver.find_elements_by_xpath('//p[@class="bold fs-15 mb-2 pr time"]')
arrivaltime
arrivaltime1=[]

for i in arrivaltime:
    arrivaltime1.append(i.text)
arrivaltime1

place=driver.find_elements_by_xpath('//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
place
place1=[]

for i in place:
    place1.append(i.text)
place1

departureplace=[]
for i in range(0,len(place1),2):
    departureplace.append(place1[i])
departureplace

Arrivalplace=[]
for i in range(1,len(place1),2):
    Arrivalplace.append(place1[i])
Arrivalplace

timmings=driver.find_elements_by_xpath('//p[@class="fs-12 bold du mb-2"]')
timmings
timmings1=[]

for i in timmings:
    timmings1.append(i.text)
timmings1    

price=driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
price
price1=[]

for i in price:
    price1.append(i.text)
price1   

stoppage=driver.find_elements_by_xpath('//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
stoppage
stoppage1=[]

for i in stoppage:
    stoppage1.append(i.text)
stoppage1  

dateSelect = "'2022-02-14'"

df4=pd.DataFrame({})
df4["Airline_Name"]=Company_name2
df4["Departure Time"]=Departuretime1
df4["Arrival time"]=arrivaltime1
df4["Departure Place"]=departureplace
df4["Arrival place"]=Arrivalplace
df4["Timmings"]=timmings1
df4["Price"]=price1
df4["Stoppages"]=stoppage1
df4['Date_of_Journey'] = dateSelect

df4

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Stoppages,Date_of_Journey
0,Go First,06:05,07:40,Mumbai,Bangalore,1h 35m,"2,124",Non Stop,'2022-02-14'
1,IndiGo,06:55,08:30,Mumbai,Bangalore,1h 35m,"2,124",Non Stop,'2022-02-14'
2,IndiGo,08:30,10:05,Mumbai,Bangalore,1h 35m,"2,124",Non Stop,'2022-02-14'
3,Go First,14:35,16:10,Mumbai,Bangalore,1h 35m,"2,124",Non Stop,'2022-02-14'
4,Go First,12:30,14:10,Mumbai,Bangalore,1h 40m,"2,124",Non Stop,'2022-02-14'
...,...,...,...,...,...,...,...,...,...
123,Air India,10:00,22:15,Mumbai,Bangalore,12h 15m,"8,478",2 Stop(s),'2022-02-14'
124,Air India,08:00,22:15,Mumbai,Bangalore,14h 15m,"8,478",2 Stop(s),'2022-02-14'
125,Vistara,07:00,17:00,Mumbai,Bangalore,10h 00m,"10,612",1 Stop,'2022-02-14'
126,Vistara,07:00,18:50,Mumbai,Bangalore,11h 50m,"10,612",1 Stop,'2022-02-14'
127,Vistara,16:05,18:15\n+ 1 day,Mumbai,Bangalore,26h 10m,"13,116",1 Stop,'2022-02-14'

# MUMBAI-CHENNAI 21-02-2022

In [12]:
driver=webdriver.Chrome(r"C:\Users\Admin\Downloads\chromedriver_win32 (2)\chromedriver.exe")
url1="https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=21%2F02%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=750183643255&version=1.1&viewName=normal"
driver.get(url1)

In [13]:
for i in url:
    SCROLL_PAUSE_TIME = 1

    # Get scroll height
    """last_height = driver.execute_script("return document.body.scrollHeight")

    this dowsnt work due to floating web elements on youtube
    """

    last_height = driver.execute_script("return document.documentElement.scrollHeight")
    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0,document.documentElement.scrollHeight);")

        # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.documentElement.scrollHeight")
        if new_height == last_height:
                 break
        last_height = new_height
        
Company_name1=driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
Company_name1
Company_name2=[]

for i in Company_name1:
    Company_name2.append(i.text)
Company_name2


Departuretime=driver.find_elements_by_xpath('//div[@class="fs-15 bold time"]')
Departuretime
Departuretime1=[]

for i in Departuretime:
    Departuretime1.append(i.text)
Departuretime1


arrivaltime=driver.find_elements_by_xpath('//p[@class="bold fs-15 mb-2 pr time"]')
arrivaltime
arrivaltime1=[]

for i in arrivaltime:
    arrivaltime1.append(i.text)
arrivaltime1

place=driver.find_elements_by_xpath('//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
place
place1=[]

for i in place:
    place1.append(i.text)
place1

departureplace=[]
for i in range(0,len(place1),2):
    departureplace.append(place1[i])
departureplace

Arrivalplace=[]
for i in range(1,len(place1),2):
    Arrivalplace.append(place1[i])
Arrivalplace

timmings=driver.find_elements_by_xpath('//p[@class="fs-12 bold du mb-2"]')
timmings
timmings1=[]

for i in timmings:
    timmings1.append(i.text)
timmings1    

price=driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
price
price1=[]

for i in price:
    price1.append(i.text)
price1   

stoppage=driver.find_elements_by_xpath('//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
stoppage
stoppage1=[]

for i in stoppage:
    stoppage1.append(i.text)
stoppage1  

dateSelect = "'2022-02-21'"

df5=pd.DataFrame({})
df5["Airline_Name"]=Company_name2
df5["Departure Time"]=Departuretime1
df5["Arrival time"]=arrivaltime1
df5["Departure Place"]=departureplace
df5["Arrival place"]=Arrivalplace
df5["Timmings"]=timmings1
df5["Price"]=price1
df5["Stoppages"]=stoppage1
df5['Date_of_Journey'] = dateSelect

df5

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Stoppages,Date_of_Journey
0,Go First,06:05,07:40,Mumbai,Bangalore,1h 35m,"2,124",Non Stop,'2022-02-21'
1,IndiGo,06:55,08:30,Mumbai,Bangalore,1h 35m,"2,124",Non Stop,'2022-02-21'
2,IndiGo,08:30,10:05,Mumbai,Bangalore,1h 35m,"2,124",Non Stop,'2022-02-21'
3,Go First,14:35,16:10,Mumbai,Bangalore,1h 35m,"2,124",Non Stop,'2022-02-21'
4,Go First,12:30,14:10,Mumbai,Bangalore,1h 40m,"2,124",Non Stop,'2022-02-21'
...,...,...,...,...,...,...,...,...,...
142,Vistara,06:00,23:20,Mumbai,Bangalore,17h 20m,"9,125",2 Stop(s),'2022-02-21'
143,Vistara,06:00,23:20,Mumbai,Bangalore,17h 20m,"9,125",2 Stop(s),'2022-02-21'
144,Vistara,06:00,18:15,Mumbai,Bangalore,12h 15m,"12,015",1 Stop,'2022-02-21'
145,Vistara,16:05,18:15\n+ 1 day,Mumbai,Bangalore,26h 10m,"12,015",1 Stop,'2022-02-21'
146,Go First,06:00,15:10,Mumbai,Bangalore,9h 10m,"12,847",2 Stop(s),'2022-02-21'

# MUMBAI-BANGALORE 28-02-2022

In [14]:
driver=webdriver.Chrome(r"C:\Users\Admin\Downloads\chromedriver_win32 (2)\chromedriver.exe")
url1="https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=28%2F02%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=1253972278287&version=1.1&viewName=normal"
driver.get(url1)

In [15]:
for i in url:
    SCROLL_PAUSE_TIME = 1

    # Get scroll height
    """last_height = driver.execute_script("return document.body.scrollHeight")

    this dowsnt work due to floating web elements on youtube
    """

    last_height = driver.execute_script("return document.documentElement.scrollHeight")
    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0,document.documentElement.scrollHeight);")

        # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.documentElement.scrollHeight")
        if new_height == last_height:
                 break
        last_height = new_height
        
Company_name1=driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
Company_name1
Company_name2=[]

for i in Company_name1:
    Company_name2.append(i.text)
Company_name2


Departuretime=driver.find_elements_by_xpath('//div[@class="fs-15 bold time"]')
Departuretime
Departuretime1=[]

for i in Departuretime:
    Departuretime1.append(i.text)
Departuretime1


arrivaltime=driver.find_elements_by_xpath('//p[@class="bold fs-15 mb-2 pr time"]')
arrivaltime
arrivaltime1=[]

for i in arrivaltime:
    arrivaltime1.append(i.text)
arrivaltime1

place=driver.find_elements_by_xpath('//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
place
place1=[]

for i in place:
    place1.append(i.text)
place1

departureplace=[]
for i in range(0,len(place1),2):
    departureplace.append(place1[i])
departureplace

Arrivalplace=[]
for i in range(1,len(place1),2):
    Arrivalplace.append(place1[i])
Arrivalplace

timmings=driver.find_elements_by_xpath('//p[@class="fs-12 bold du mb-2"]')
timmings
timmings1=[]

for i in timmings:
    timmings1.append(i.text)
timmings1    

price=driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
price
price1=[]

for i in price:
    price1.append(i.text)
price1   

stoppage=driver.find_elements_by_xpath('//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
stoppage
stoppage1=[]

for i in stoppage:
    stoppage1.append(i.text)
stoppage1  

dateSelect = "'2022-02-28'"

df6=pd.DataFrame({})
df6["Airline_Name"]=Company_name2
df6["Departure Time"]=Departuretime1
df6["Arrival time"]=arrivaltime1
df6["Departure Place"]=departureplace
df6["Arrival place"]=Arrivalplace
df6["Timmings"]=timmings1
df6["Price"]=price1
df6["Stoppages"]=stoppage1
df6['Date_of_Journey'] = dateSelect

df6

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Stoppages,Date_of_Journey
0,Go First,06:05,07:40,Mumbai,Bangalore,1h 35m,"2,124",Non Stop,'2022-02-28'
1,IndiGo,06:55,08:30,Mumbai,Bangalore,1h 35m,"2,124",Non Stop,'2022-02-28'
2,IndiGo,08:30,10:05,Mumbai,Bangalore,1h 35m,"2,124",Non Stop,'2022-02-28'
3,Go First,14:35,16:10,Mumbai,Bangalore,1h 35m,"2,124",Non Stop,'2022-02-28'
4,Go First,12:30,14:10,Mumbai,Bangalore,1h 40m,"2,124",Non Stop,'2022-02-28'
...,...,...,...,...,...,...,...,...,...
141,Vistara,06:00,22:40,Mumbai,Bangalore,16h 40m,"9,125",2 Stop(s),'2022-02-28'
142,Vistara,06:00,23:20,Mumbai,Bangalore,17h 20m,"9,125",2 Stop(s),'2022-02-28'
143,Vistara,06:00,23:20,Mumbai,Bangalore,17h 20m,"9,125",2 Stop(s),'2022-02-28'
144,Vistara,06:00,18:15,Mumbai,Bangalore,12h 15m,"12,015",1 Stop,'2022-02-28'
145,Go First,06:00,15:10,Mumbai,Bangalore,9h 10m,"12,847",2 Stop(s),'2022-02-28'

In [17]:
# append method
df7= df1.append([df2,df3,df4,df5,df6])
df7

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Stoppages,Date_of_Journey
0,Go First,20:35,22:20,Mumbai,Bangalore,1h 45m,"5,102",Non Stop,'2022-01-31'
1,Go First,05:25,10:25,Mumbai,Bangalore,5h 00m,"5,102",1 Stop,'2022-01-31'
2,Go First,13:30,21:25,Mumbai,Bangalore,7h 55m,"5,102",1 Stop,'2022-01-31'
3,Go First,19:15,10:20\n+ 1 day,Mumbai,Bangalore,15h 05m,"5,102",1 Stop,'2022-01-31'
4,SpiceJet,15:30,09:00\n+ 1 day,Mumbai,Bangalore,17h 30m,"5,102",1 Stop,'2022-01-31'
...,...,...,...,...,...,...,...,...,...
141,Vistara,06:00,22:40,Mumbai,Bangalore,16h 40m,"9,125",2 Stop(s),'2022-02-28'
142,Vistara,06:00,23:20,Mumbai,Bangalore,17h 20m,"9,125",2 Stop(s),'2022-02-28'
143,Vistara,06:00,23:20,Mumbai,Bangalore,17h 20m,"9,125",2 Stop(s),'2022-02-28'
144,Vistara,06:00,18:15,Mumbai,Bangalore,12h 15m,"12,015",1 Stop,'2022-02-28'
145,Go First,06:00,15:10,Mumbai,Bangalore,9h 10m,"12,847",2 Stop(s),'2022-02-28'

In [18]:
file_name='MUMBAI-BANGALORE.xlsx'
df7.to_excel(file_name)
print('DataFrame is written to Excel File successfully')

DataFrame is written to Excel File successfully