# MUMBAI-KOLKATTA-30-01-2022

In [1]:
!pip install selenium
!pip install undetected-chromedriver
     

import time
import warnings
warnings.filterwarnings('ignore')

Requirement already satisfied: selenium in c:\users\admin\anaconda3\lib\site-packages (3.141.0)
Requirement already satisfied: urllib3 in c:\users\admin\anaconda3\lib\site-packages (from selenium) (1.25.11)
Requirement already satisfied: undetected-chromedriver in c:\users\admin\anaconda3\lib\site-packages (3.0.6)
Requirement already satisfied: selenium in c:\users\admin\anaconda3\lib\site-packages (from undetected-chromedriver) (3.141.0)
Requirement already satisfied: requests in c:\users\admin\anaconda3\lib\site-packages (from undetected-chromedriver) (2.24.0)
Requirement already satisfied: websockets in c:\users\admin\anaconda3\lib\site-packages (from undetected-chromedriver) (10.1)
Requirement already satisfied: urllib3 in c:\users\admin\anaconda3\lib\site-packages (from selenium->undetected-chromedriver) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\anaconda3\lib\site-packages (from requests->undetected-chromedriver) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\admin\anaconda3\lib\site-packages (from requests->undetected-chromedriver) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from requests->undetected-chromedriver) (2.10)

In [2]:
import selenium
import pandas as pd
from selenium import webdriver 
from selenium.common.exceptions import  StaleElementReferenceException,ElementClickInterceptedException
from selenium.common.exceptions import  NoSuchElementException,NoSuchWindowException

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

In [3]:
driver=webdriver.Chrome(r"C:\Users\Admin\Downloads\chromedriver_win32 (2)\chromedriver.exe")
url="https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=30%2F01%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=1544057204623&version=1.1&viewName=normal"
driver.get(url)

In [4]:
for i in url:
    SCROLL_PAUSE_TIME = 1

    # Get scroll height
    """last_height = driver.execute_script("return document.body.scrollHeight")

    this dowsnt work due to floating web elements on youtube
    """

    last_height = driver.execute_script("return document.documentElement.scrollHeight")
    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0,document.documentElement.scrollHeight);")

        # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.documentElement.scrollHeight")
        if new_height == last_height:
                 break
        last_height = new_height
        
Company_name1=driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
Company_name1
Company_name2=[]

for i in Company_name1:
    Company_name2.append(i.text)
Company_name2


Departuretime=driver.find_elements_by_xpath('//div[@class="fs-15 bold time"]')
Departuretime
Departuretime1=[]

for i in Departuretime:
    Departuretime1.append(i.text)
Departuretime1


arrivaltime=driver.find_elements_by_xpath('//p[@class="bold fs-15 mb-2 pr time"]')
arrivaltime
arrivaltime1=[]

for i in arrivaltime:
    arrivaltime1.append(i.text)
arrivaltime1

place=driver.find_elements_by_xpath('//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
place
place1=[]

for i in place:
    place1.append(i.text)
place1

departureplace=[]
for i in range(0,len(place1),2):
    departureplace.append(place1[i])
departureplace

Arrivalplace=[]
for i in range(1,len(place1),2):
    Arrivalplace.append(place1[i])
Arrivalplace

timmings=driver.find_elements_by_xpath('//p[@class="fs-12 bold du mb-2"]')
timmings
timmings1=[]

for i in timmings:
    timmings1.append(i.text)
timmings1    

price=driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
price
price1=[]

for i in price:
    price1.append(i.text)
price1   

stoppage=driver.find_elements_by_xpath('//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
stoppage
stoppage1=[]

for i in stoppage:
    stoppage1.append(i.text)
stoppage1  

dateSelect = "'2022-01-30'"

df=pd.DataFrame({})
df["Airline_Name"]=Company_name2
df["Departure Time"]=Departuretime1
df["Arrival time"]=arrivaltime1
df["Departure Place"]=departureplace
df["Arrival place"]=Arrivalplace
df["Timmings"]=timmings1
df["Price"]=price1
df["Stoppages"]=stoppage1
df['Date_of_Journey'] = dateSelect

df

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Stoppages,Date_of_Journey
0,SpiceJet,18:40,23:20,Mumbai,Kolkata,4h 40m,"7,412",1 Stop,'2022-01-30'
1,SpiceJet,15:30,21:25,Mumbai,Kolkata,5h 55m,"7,412",1 Stop,'2022-01-30'
2,SpiceJet,14:55,21:30,Mumbai,Kolkata,6h 35m,"7,412",1 Stop,'2022-01-30'
3,Go First,19:15,08:40\n+ 1 day,Mumbai,Kolkata,13h 25m,"7,412",1 Stop,'2022-01-30'
4,SpiceJet,22:20,23:00\n+ 1 day,Mumbai,Kolkata,24h 40m,"7,412",1 Stop,'2022-01-30'
...,...,...,...,...,...,...,...,...,...
56,Air India,16:00,17:35\n+ 1 day,Mumbai,Kolkata,25h 35m,"13,926",3 Stop(s),'2022-01-30'
57,IndiGo,17:15,00:35\n+ 1 day,Mumbai,Kolkata,7h 20m,"15,602",1 Stop,'2022-01-30'
58,Vistara,16:00,08:35\n+ 1 day,Mumbai,Kolkata,16h 35m,"15,854",2 Stop(s),'2022-01-30'
59,Vistara,16:00,09:35\n+ 1 day,Mumbai,Kolkata,17h 35m,"16,032",2 Stop(s),'2022-01-30'
60,Vistara,16:05,19:35\n+ 1 day,Mumbai,Kolkata,27h 30m,"20,748",2 Stop(s),'2022-01-30'

# DELHI-KOLKATTA 31-01-2022

In [5]:
driver=webdriver.Chrome(r"C:\Users\Admin\Downloads\chromedriver_win32 (2)\chromedriver.exe")
url="https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=31%2F01%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=143139442240&version=1.1&viewName=normal"
driver.get(url)

In [6]:
for i in url:
    SCROLL_PAUSE_TIME = 1

    # Get scroll height
    """last_height = driver.execute_script("return document.body.scrollHeight")

    this dowsnt work due to floating web elements on youtube
    """

    last_height = driver.execute_script("return document.documentElement.scrollHeight")
    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0,document.documentElement.scrollHeight);")

        # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.documentElement.scrollHeight")
        if new_height == last_height:
                 break
        last_height = new_height
        
Company_name1=driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
Company_name1
Company_name2=[]

for i in Company_name1:
    Company_name2.append(i.text)
Company_name2


Departuretime=driver.find_elements_by_xpath('//div[@class="fs-15 bold time"]')
Departuretime
Departuretime1=[]

for i in Departuretime:
    Departuretime1.append(i.text)
Departuretime1


arrivaltime=driver.find_elements_by_xpath('//p[@class="bold fs-15 mb-2 pr time"]')
arrivaltime
arrivaltime1=[]

for i in arrivaltime:
    arrivaltime1.append(i.text)
arrivaltime1

place=driver.find_elements_by_xpath('//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
place
place1=[]

for i in place:
    place1.append(i.text)
place1

departureplace=[]
for i in range(0,len(place1),2):
    departureplace.append(place1[i])
departureplace

Arrivalplace=[]
for i in range(1,len(place1),2):
    Arrivalplace.append(place1[i])
Arrivalplace

timmings=driver.find_elements_by_xpath('//p[@class="fs-12 bold du mb-2"]')
timmings
timmings1=[]

for i in timmings:
    timmings1.append(i.text)
timmings1    

price=driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
price
price1=[]

for i in price:
    price1.append(i.text)
price1   

stoppage=driver.find_elements_by_xpath('//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
stoppage
stoppage1=[]

for i in stoppage:
    stoppage1.append(i.text)
stoppage1  

dateSelect = "'2022-01-31'"

df1=pd.DataFrame({})
df1["Airline_Name"]=Company_name2
df1["Departure Time"]=Departuretime1
df1["Arrival time"]=arrivaltime1
df1["Departure Place"]=departureplace
df1["Arrival place"]=Arrivalplace
df1["Timmings"]=timmings1
df1["Price"]=price1
df1["Stoppages"]=stoppage1
df1['Date_of_Journey'] = dateSelect

df1

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Stoppages,Date_of_Journey
0,Go First,21:00,23:35,Mumbai,Kolkata,2h 35m,"7,412",Non Stop,'2022-01-31'
1,SpiceJet,06:15,08:55,Mumbai,Kolkata,2h 40m,"7,412",Non Stop,'2022-01-31'
2,SpiceJet,18:40,21:25,Mumbai,Kolkata,2h 45m,"7,412",Non Stop,'2022-01-31'
3,SpiceJet,10:15,23:00,Mumbai,Kolkata,12h 45m,"7,412",1 Stop,'2022-01-31'
4,SpiceJet,05:55,21:25,Mumbai,Kolkata,15h 30m,"7,412",1 Stop,'2022-01-31'
5,SpiceJet,07:20,23:00,Mumbai,Kolkata,15h 40m,"7,412",1 Stop,'2022-01-31'
6,SpiceJet,13:00,14:20\n+ 1 day,Mumbai,Kolkata,25h 20m,"7,412",1 Stop,'2022-01-31'
7,IndiGo,06:30,09:05,Mumbai,Kolkata,2h 35m,"7,413",Non Stop,'2022-01-31'
8,Air India,06:10,08:50,Mumbai,Kolkata,2h 40m,"7,413",Non Stop,'2022-01-31'
9,Vistara,07:00,09:40,Mumbai,Kolkata,2h 40m,"7,413",Non Stop,'2022-01-31'
10,Vistara,14:05,16:55,Mumbai,Kolkata,2h 50m,"7,518",Non Stop,'2022-01-31'
11,IndiGo,12:55,15:35,Mumbai,Kolkata,2h 40m,"7,833",Non Stop,'2022-01-31'
12,IndiGo,07:35,10:15,Mumbai,Kolkata,2h 40m,"8,673",Non Stop,'2022-01-31'
13,IndiGo,16:20,22:40,Mumbai,Kolkata,6h 20m,"8,883",1 Stop,'2022-01-31'
14,IndiGo,12:45,19:15,Mumbai,Kolkata,6h 30m,"8,883",1 Stop,'2022-01-31'
15,IndiGo,10:45,19:15,Mumbai,Kolkata,8h 30m,"8,883",1 Stop,'2022-01-31'
16,IndiGo,12:45,22:40,Mumbai,Kolkata,9h 55m,"8,883",1 Stop,'2022-01-31'
17,IndiGo,17:40,20:10,Mumbai,Kolkata,2h 30m,"9,093",Non Stop,'2022-01-31'
18,Air India,20:15,08:05\n+ 1 day,Mumbai,Kolkata,11h 50m,"9,618",1 Stop,'2022-01-31'
19,IndiGo,11:40,20:55,Mumbai,Kolkata,9h 15m,"9,671",1 Stop,'2022-01-31'
20,Go First,19:15,08:40\n+ 1 day,Mumbai,Kolkata,13h 25m,"9,698",1 Stop,'2022-01-31'
21,IndiGo,12:20,22:25,Mumbai,Kolkata,10h 05m,"9,723",1 Stop,'2022-01-31'
22,Air India,09:30,17:35,Mumbai,Kolkata,8h 05m,"9,828",2 Stop(s),'2022-01-31'
23,Air India,16:45,05:15\n+ 1 day,Mumbai,Kolkata,12h 30m,"9,828",1 Stop,'2022-01-31'
24,Air India,09:30,05:15\n+ 1 day,Mumbai,Kolkata,19h 45m,"9,828",1 Stop,'2022-01-31'

# MUMBAI-KOLKATTA 01-02-2022

In [7]:
driver=webdriver.Chrome(r"C:\Users\Admin\Downloads\chromedriver_win32 (2)\chromedriver.exe")
url1="https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=01%2F02%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=1412552079070&version=1.1&viewName=normal"
driver.get(url1)

In [8]:
for i in url:
    SCROLL_PAUSE_TIME = 1

    # Get scroll height
    """last_height = driver.execute_script("return document.body.scrollHeight")

    this dowsnt work due to floating web elements on youtube
    """

    last_height = driver.execute_script("return document.documentElement.scrollHeight")
    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0,document.documentElement.scrollHeight);")

        # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.documentElement.scrollHeight")
        if new_height == last_height:
                 break
        last_height = new_height
        
Company_name1=driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
Company_name1
Company_name2=[]

for i in Company_name1:
    Company_name2.append(i.text)
Company_name2


Departuretime=driver.find_elements_by_xpath('//div[@class="fs-15 bold time"]')
Departuretime
Departuretime1=[]

for i in Departuretime:
    Departuretime1.append(i.text)
Departuretime1


arrivaltime=driver.find_elements_by_xpath('//p[@class="bold fs-15 mb-2 pr time"]')
arrivaltime
arrivaltime1=[]

for i in arrivaltime:
    arrivaltime1.append(i.text)
arrivaltime1

place=driver.find_elements_by_xpath('//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
place
place1=[]

for i in place:
    place1.append(i.text)
place1

departureplace=[]
for i in range(0,len(place1),2):
    departureplace.append(place1[i])
departureplace

Arrivalplace=[]
for i in range(1,len(place1),2):
    Arrivalplace.append(place1[i])
Arrivalplace

timmings=driver.find_elements_by_xpath('//p[@class="fs-12 bold du mb-2"]')
timmings
timmings1=[]

for i in timmings:
    timmings1.append(i.text)
timmings1    

price=driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
price
price1=[]

for i in price:
    price1.append(i.text)
price1   

stoppage=driver.find_elements_by_xpath('//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
stoppage
stoppage1=[]

for i in stoppage:
    stoppage1.append(i.text)
stoppage1  

dateSelect = "'2022-02-01'"

df2=pd.DataFrame({})
df2["Airline_Name"]=Company_name2
df2["Departure Time"]=Departuretime1
df2["Arrival time"]=arrivaltime1
df2["Departure Place"]=departureplace
df2["Arrival place"]=Arrivalplace
df2["Timmings"]=timmings1
df2["Price"]=price1
df2["Stoppages"]=stoppage1
df2['Date_of_Journey'] = dateSelect

df2

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Stoppages,Date_of_Journey
0,Go First,22:40,08:40\n+ 1 day,Mumbai,Kolkata,10h 00m,"7,412",1 Stop,'2022-02-01'
1,Go First,19:15,08:40\n+ 1 day,Mumbai,Kolkata,13h 25m,"7,412",1 Stop,'2022-02-01'
2,Go First,18:10,08:40\n+ 1 day,Mumbai,Kolkata,14h 30m,"7,412",1 Stop,'2022-02-01'
3,Air India,07:55,12:10,Mumbai,Kolkata,4h 15m,"8,253",1 Stop,'2022-02-01'
4,Vistara,12:25,16:50,Mumbai,Kolkata,4h 25m,"8,253",1 Stop,'2022-02-01'
...,...,...,...,...,...,...,...,...,...
75,Vistara,12:25,20:45,Mumbai,Kolkata,8h 20m,"21,273",2 Stop(s),'2022-02-01'
76,Vistara,11:55,20:45,Mumbai,Kolkata,8h 50m,"21,273",2 Stop(s),'2022-02-01'
77,Vistara,10:25,20:45,Mumbai,Kolkata,10h 20m,"21,273",2 Stop(s),'2022-02-01'
78,Vistara,08:45,20:45,Mumbai,Kolkata,12h 00m,"21,273",2 Stop(s),'2022-02-01'
79,Vistara,12:15,20:45,Mumbai,Kolkata,8h 30m,"23,478",3 Stop(s),'2022-02-01'

# MUMBAI-KOLKATTA 07-02-2022

In [9]:
driver=webdriver.Chrome(r"C:\Users\Admin\Downloads\chromedriver_win32 (2)\chromedriver.exe")
url1="https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=07%2F02%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=31153476231&version=1.1&viewName=normal"
driver.get(url1)

In [10]:
for i in url:
    SCROLL_PAUSE_TIME = 1

    # Get scroll height
    """last_height = driver.execute_script("return document.body.scrollHeight")

    this dowsnt work due to floating web elements on youtube
    """

    last_height = driver.execute_script("return document.documentElement.scrollHeight")
    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0,document.documentElement.scrollHeight);")

        # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.documentElement.scrollHeight")
        if new_height == last_height:
                 break
        last_height = new_height
        
Company_name1=driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
Company_name1
Company_name2=[]

for i in Company_name1:
    Company_name2.append(i.text)
Company_name2


Departuretime=driver.find_elements_by_xpath('//div[@class="fs-15 bold time"]')
Departuretime
Departuretime1=[]

for i in Departuretime:
    Departuretime1.append(i.text)
Departuretime1


arrivaltime=driver.find_elements_by_xpath('//p[@class="bold fs-15 mb-2 pr time"]')
arrivaltime
arrivaltime1=[]

for i in arrivaltime:
    arrivaltime1.append(i.text)
arrivaltime1

place=driver.find_elements_by_xpath('//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
place
place1=[]

for i in place:
    place1.append(i.text)
place1

departureplace=[]
for i in range(0,len(place1),2):
    departureplace.append(place1[i])
departureplace

Arrivalplace=[]
for i in range(1,len(place1),2):
    Arrivalplace.append(place1[i])
Arrivalplace

timmings=driver.find_elements_by_xpath('//p[@class="fs-12 bold du mb-2"]')
timmings
timmings1=[]

for i in timmings:
    timmings1.append(i.text)
timmings1    

price=driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
price
price1=[]

for i in price:
    price1.append(i.text)
price1   

stoppage=driver.find_elements_by_xpath('//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
stoppage
stoppage1=[]

for i in stoppage:
    stoppage1.append(i.text)
stoppage1  

dateSelect = "'2022-02-07'"

df3=pd.DataFrame({})
df3["Airline_Name"]=Company_name2
df3["Departure Time"]=Departuretime1
df3["Arrival time"]=arrivaltime1
df3["Departure Place"]=departureplace
df3["Arrival place"]=Arrivalplace
df3["Timmings"]=timmings1
df3["Price"]=price1
df3["Stoppages"]=stoppage1
df3['Date_of_Journey'] = dateSelect

df3

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Stoppages,Date_of_Journey
0,Go First,05:00,07:30,Mumbai,Kolkata,2h 30m,"7,412",Non Stop,'2022-02-07'
1,Go First,21:00,23:35,Mumbai,Kolkata,2h 35m,"7,412",Non Stop,'2022-02-07'
2,SpiceJet,06:15,08:55,Mumbai,Kolkata,2h 40m,"7,412",Non Stop,'2022-02-07'
3,SpiceJet,18:40,21:25,Mumbai,Kolkata,2h 45m,"7,412",Non Stop,'2022-02-07'
4,SpiceJet,14:55,21:30,Mumbai,Kolkata,6h 35m,"7,412",1 Stop,'2022-02-07'
...,...,...,...,...,...,...,...,...,...
109,Vistara,07:00,19:35,Mumbai,Kolkata,12h 35m,"18,648",1 Stop,'2022-02-07'
110,SpiceJet,19:50,09:05\n+ 1 day,Mumbai,Kolkata,13h 15m,"19,251",1 Stop,'2022-02-07'
111,Vistara,12:15,19:35,Mumbai,Kolkata,7h 20m,"19,488",2 Stop(s),'2022-02-07'
112,Vistara,16:05,20:45\n+ 1 day,Mumbai,Kolkata,28h 40m,"19,803",2 Stop(s),'2022-02-07'
113,SpiceJet,05:55,09:05\n+ 1 day,Mumbai,Kolkata,27h 10m,"22,191",1 Stop,'2022-02-07'

# MUMBAI-KOLKATTA 14-02-2022

In [11]:
driver=webdriver.Chrome(r"C:\Users\Admin\Downloads\chromedriver_win32 (2)\chromedriver.exe")
url1="https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=BOM&originCountry=IN&destination=CCU&destinationCountry=IN&flight_depart_date=14%2F02%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=1316230024109"
driver.get(url1)

In [12]:
for i in url:
    SCROLL_PAUSE_TIME = 1

    # Get scroll height
    """last_height = driver.execute_script("return document.body.scrollHeight")

    this dowsnt work due to floating web elements on youtube
    """

    last_height = driver.execute_script("return document.documentElement.scrollHeight")
    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0,document.documentElement.scrollHeight);")

        # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.documentElement.scrollHeight")
        if new_height == last_height:
                 break
        last_height = new_height
        
Company_name1=driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
Company_name1
Company_name2=[]

for i in Company_name1:
    Company_name2.append(i.text)
Company_name2


Departuretime=driver.find_elements_by_xpath('//div[@class="fs-15 bold time"]')
Departuretime
Departuretime1=[]

for i in Departuretime:
    Departuretime1.append(i.text)
Departuretime1


arrivaltime=driver.find_elements_by_xpath('//p[@class="bold fs-15 mb-2 pr time"]')
arrivaltime
arrivaltime1=[]

for i in arrivaltime:
    arrivaltime1.append(i.text)
arrivaltime1

place=driver.find_elements_by_xpath('//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
place
place1=[]

for i in place:
    place1.append(i.text)
place1

departureplace=[]
for i in range(0,len(place1),2):
    departureplace.append(place1[i])
departureplace

Arrivalplace=[]
for i in range(1,len(place1),2):
    Arrivalplace.append(place1[i])
Arrivalplace

timmings=driver.find_elements_by_xpath('//p[@class="fs-12 bold du mb-2"]')
timmings
timmings1=[]

for i in timmings:
    timmings1.append(i.text)
timmings1    

price=driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
price
price1=[]

for i in price:
    price1.append(i.text)
price1   

stoppage=driver.find_elements_by_xpath('//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
stoppage
stoppage1=[]

for i in stoppage:
    stoppage1.append(i.text)
stoppage1  

dateSelect = "'2022-02-14'"

df4=pd.DataFrame({})
df4["Airline_Name"]=Company_name2
df4["Departure Time"]=Departuretime1
df4["Arrival time"]=arrivaltime1
df4["Departure Place"]=departureplace
df4["Arrival place"]=Arrivalplace
df4["Timmings"]=timmings1
df4["Price"]=price1
df4["Stoppages"]=stoppage1
df4['Date_of_Journey'] = dateSelect

df4

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Stoppages,Date_of_Journey
0,Air Asia,13:05,19:15,Mumbai,Kolkata,6h 10m,"2,833",2 Stop(s),'2022-02-14'
1,Air Asia,13:05,21:05,Mumbai,Kolkata,8h 00m,"2,833",1 Stop,'2022-02-14'
2,Air Asia,22:00,07:10\n+ 1 day,Mumbai,Kolkata,9h 10m,"2,833",1 Stop,'2022-02-14'
3,Air Asia,14:55,01:35\n+ 1 day,Mumbai,Kolkata,10h 40m,"2,833",2 Stop(s),'2022-02-14'
4,Go First,05:00,07:30,Mumbai,Kolkata,2h 30m,"2,834",Non Stop,'2022-02-14'
...,...,...,...,...,...,...,...,...,...
124,Air India,15:35,05:15\n+ 1 day,Mumbai,Kolkata,13h 40m,"8,184",3 Stop(s),'2022-02-14'
125,Air India,10:00,05:15\n+ 1 day,Mumbai,Kolkata,19h 15m,"8,184",2 Stop(s),'2022-02-14'
126,Air India,21:30,20:05\n+ 1 day,Mumbai,Kolkata,22h 35m,"9,323",4 Stop(s),'2022-02-14'
127,IndiGo,09:20,17:25,Mumbai,Kolkata,8h 05m,"14,854",1 Stop,'2022-02-14'
128,Vistara,16:05,19:35\n+ 1 day,Mumbai,Kolkata,27h 30m,"14,861",2 Stop(s),'2022-02-14'

# MUMBAI-KOLKATTA 21-02-2022

In [13]:
driver=webdriver.Chrome(r"C:\Users\Admin\Downloads\chromedriver_win32 (2)\chromedriver.exe")
url1="https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=21%2F02%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=401333419426&version=1.1&viewName=normal"
driver.get(url1)

In [14]:
for i in url:
    SCROLL_PAUSE_TIME = 1

    # Get scroll height
    """last_height = driver.execute_script("return document.body.scrollHeight")

    this dowsnt work due to floating web elements on youtube
    """

    last_height = driver.execute_script("return document.documentElement.scrollHeight")
    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0,document.documentElement.scrollHeight);")

        # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.documentElement.scrollHeight")
        if new_height == last_height:
                 break
        last_height = new_height
        
Company_name1=driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
Company_name1
Company_name2=[]

for i in Company_name1:
    Company_name2.append(i.text)
Company_name2


Departuretime=driver.find_elements_by_xpath('//div[@class="fs-15 bold time"]')
Departuretime
Departuretime1=[]

for i in Departuretime:
    Departuretime1.append(i.text)
Departuretime1


arrivaltime=driver.find_elements_by_xpath('//p[@class="bold fs-15 mb-2 pr time"]')
arrivaltime
arrivaltime1=[]

for i in arrivaltime:
    arrivaltime1.append(i.text)
arrivaltime1

place=driver.find_elements_by_xpath('//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
place
place1=[]

for i in place:
    place1.append(i.text)
place1

departureplace=[]
for i in range(0,len(place1),2):
    departureplace.append(place1[i])
departureplace

Arrivalplace=[]
for i in range(1,len(place1),2):
    Arrivalplace.append(place1[i])
Arrivalplace

timmings=driver.find_elements_by_xpath('//p[@class="fs-12 bold du mb-2"]')
timmings
timmings1=[]

for i in timmings:
    timmings1.append(i.text)
timmings1    

price=driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
price
price1=[]

for i in price:
    price1.append(i.text)
price1   

stoppage=driver.find_elements_by_xpath('//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
stoppage
stoppage1=[]

for i in stoppage:
    stoppage1.append(i.text)
stoppage1  

dateSelect = "'2022-02-21'"

df5=pd.DataFrame({})
df5["Airline_Name"]=Company_name2
df5["Departure Time"]=Departuretime1
df5["Arrival time"]=arrivaltime1
df5["Departure Place"]=departureplace
df5["Arrival place"]=Arrivalplace
df5["Timmings"]=timmings1
df5["Price"]=price1
df5["Stoppages"]=stoppage1
df5['Date_of_Journey'] = dateSelect

df5

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Stoppages,Date_of_Journey
0,Air Asia,13:05,19:15,Mumbai,Kolkata,6h 10m,"2,833",2 Stop(s),'2022-02-21'
1,Air Asia,22:55,07:10\n+ 1 day,Mumbai,Kolkata,8h 15m,"2,833",1 Stop,'2022-02-21'
2,Air Asia,14:55,01:35\n+ 1 day,Mumbai,Kolkata,10h 40m,"2,833",2 Stop(s),'2022-02-21'
3,Air Asia,07:20,19:30,Mumbai,Kolkata,12h 10m,"2,833",1 Stop,'2022-02-21'
4,Go First,05:00,07:30,Mumbai,Kolkata,2h 30m,"2,834",Non Stop,'2022-02-21'
...,...,...,...,...,...,...,...,...,...
133,Air India,16:00,05:15\n+ 1 day,Mumbai,Kolkata,13h 15m,"8,184",2 Stop(s),'2022-02-21'
134,Air India,21:30,20:05\n+ 1 day,Mumbai,Kolkata,22h 35m,"9,323",4 Stop(s),'2022-02-21'
135,Vistara,06:00,19:35,Mumbai,Kolkata,13h 35m,"12,120",2 Stop(s),'2022-02-21'
136,Vistara,16:05,19:35\n+ 1 day,Mumbai,Kolkata,27h 30m,"12,120",2 Stop(s),'2022-02-21'
137,Vistara,11:25,22:45,Mumbai,Kolkata,11h 20m,"14,650",2 Stop(s),'2022-02-21'

In [15]:
# append method
df6= df.append([df1,df2,df3,df4,df5])
df6

,Airline_Name,Departure Time,Arrival time,Departure Place,Arrival place,Timmings,Price,Stoppages,Date_of_Journey
0,SpiceJet,18:40,23:20,Mumbai,Kolkata,4h 40m,"7,412",1 Stop,'2022-01-30'
1,SpiceJet,15:30,21:25,Mumbai,Kolkata,5h 55m,"7,412",1 Stop,'2022-01-30'
2,SpiceJet,14:55,21:30,Mumbai,Kolkata,6h 35m,"7,412",1 Stop,'2022-01-30'
3,Go First,19:15,08:40\n+ 1 day,Mumbai,Kolkata,13h 25m,"7,412",1 Stop,'2022-01-30'
4,SpiceJet,22:20,23:00\n+ 1 day,Mumbai,Kolkata,24h 40m,"7,412",1 Stop,'2022-01-30'
...,...,...,...,...,...,...,...,...,...
133,Air India,16:00,05:15\n+ 1 day,Mumbai,Kolkata,13h 15m,"8,184",2 Stop(s),'2022-02-21'
134,Air India,21:30,20:05\n+ 1 day,Mumbai,Kolkata,22h 35m,"9,323",4 Stop(s),'2022-02-21'
135,Vistara,06:00,19:35,Mumbai,Kolkata,13h 35m,"12,120",2 Stop(s),'2022-02-21'
136,Vistara,16:05,19:35\n+ 1 day,Mumbai,Kolkata,27h 30m,"12,120",2 Stop(s),'2022-02-21'
137,Vistara,11:25,22:45,Mumbai,Kolkata,11h 20m,"14,650",2 Stop(s),'2022-02-21'

In [16]:
file_name='MUMBAI-KOLKATTA.xlsx'
df6.to_excel(file_name)
print('DataFrame is written to Excel File successfully')

DataFrame is written to Excel File successfully